In [22]:
import numpy as np
import pandas as pd
import plotly.express as px

In [23]:
FWD_MS_COL = "forward_ms"
BWD_MS_COL = "backward_ms"
FWD_MEM_COL = "forward_memory_mb"
BWD_MEM_COL = "backward_memory_mb"
MS_TOTAL = "ms_total"

CONV_COL = "conv_type"
DATASET_COL = "dataset"
BACKEND_COL = "backend"
HEADS_COL = "heads"
FEATURE_DIM_COL = "feature_dim"

In [24]:
REORDERING_COL = "graph_reordering_partition_size"

# other columns used for tuning parameters

In [25]:
BASELINE = "dgl"

def add_speedup_columns(df_in: pd.DataFrame, baseline: str = BASELINE) -> pd.DataFrame:
    """
    For each (dataset, feature_dim, heads) triple, compute speedup
    vs `baseline` separately for forward_ms and backward_ms.
    """
    df = df_in.copy()
    idx_cols = [CONV_COL, DATASET_COL, FEATURE_DIM_COL, HEADS_COL, REORDERING_COL]

    for metric in [FWD_MS_COL, BWD_MS_COL, FWD_MEM_COL, BWD_MEM_COL, MS_TOTAL]:
        base_col = f"{metric}_baseline_{baseline}"
        speed_col = f"{metric}_speedup_vs_{baseline}"
        df[base_col] = np.nan
        df[speed_col] = np.nan

        for key, group in df.groupby(idx_cols):
            base_rows = group[group["backend"] == baseline]
            if base_rows.empty:
                continue
            base_val = base_rows.iloc[0][metric]
            if not np.isfinite(base_val) or base_val <= 0:
                continue

            mask = (
                (df[CONV_COL] == key[0]) &
                (df[DATASET_COL] == key[1]) &
                (df[FEATURE_DIM_COL] == key[2]) &
                (df[HEADS_COL] == key[3]) &
                (df[REORDERING_COL] == key[4])
            )
            df.loc[mask, base_col] = base_val
            df.loc[mask, speed_col] = base_val / df.loc[mask, metric]

    return df

In [ ]:
gcn_df = pd.concat([
    pd.read_csv("/home/fvelikon/projects/cuda_exp/out/gcn_no_reordering", index_col=0),
    pd.read_csv("/home/fvelikon/projects/cuda_exp/out/gcn_torch_native", index_col=0),
    pd.read_csv("/home/fvelikon/projects/cuda_exp/out/gcn_cusoarse_with_precompute_bwd", index_col=0),
    pd.read_csv("/home/fvelikon/projects/cuda_exp/out/gcn_partition", index_col=0),
])
gcn_df[HEADS_COL] = 1

# min_aggr_new_fp32
# MIN AGGR:
min_aggr_df = pd.concat([
    pd.read_csv("/home/fvelikon/projects/cuda_exp/out/min_aggr_no_reordering", index_col=0),
    pd.read_csv("/home/fvelikon/projects/cuda_exp/out/min_aggr_partition", index_col=0),
    pd.read_csv("/home/fvelikon/projects/cuda_exp/out/min_aggr_new_fp32", index_col=0),
])
min_aggr_df[HEADS_COL] = 1

#gatv2

gatv2_df = pd.concat([
    pd.read_csv("/home/fvelikon/projects/cuda_exp/out/test_graph_reordering", index_col=0),
    pd.read_csv("/home/fvelikon/projects/cuda_exp/out/gat_v2_no_reordering", index_col=0),
    pd.read_csv("/home/fvelikon/projects/cuda_exp/out/gatv2_partition", index_col=0),
    pd.read_csv("/home/fvelikon/projects/cuda_exp/out/gat_v2_cuda_new_1", index_col=0),
    pd.read_csv("/home/fvelikon/projects/cuda_exp/out/gat_v2_cuda_new_2", index_col=0),
    pd.read_csv("/home/fvelikon/projects/cuda_exp/out/gat_v2_cuda_new_3", index_col=0),
])


# graph transformer
gt_df = pd.concat([
    pd.read_csv("/home/fvelikon/projects/cuda_exp/out/gt_new", index_col=0),
    pd.read_csv("/home/fvelikon/projects/cuda_exp/out/gt_cuda_new", index_col=0),
    pd.read_csv("/home/fvelikon/projects/cuda_exp/out/gt_partition", index_col=0),
    pd.read_csv("/home/fvelikon/projects/cuda_exp/out/gt_dfgnn", index_col=0),
])


df = pd.concat([
    gcn_df,
    min_aggr_df,
    gatv2_df,
    gt_df,
])

In [27]:
df[MS_TOTAL] = df[FWD_MS_COL] + df[BWD_MS_COL]
df = add_speedup_columns(df, BASELINE)
df["density"] = df["num_edges"] / df["num_nodes"] / (df["num_nodes"] - 1)
df["average_node_degree"] = df["num_edges"] / df["num_nodes"]

In [28]:
def build_speedup_table_with_dataset_index(
    df_speed: pd.DataFrame,
    baseline: str,
) -> pd.DataFrame:
    """
    Build a single speedup table with a MultiIndex including dataset.

    Index:
        ('conv_type', 'dataset', 'heads', 'feature_dim')  if 'heads' in df_speed.columns
        ('conv_type', 'dataset', 'feature_dim')          otherwise

    Columns:
        MultiIndex (metric_short, backend), where metric_short ∈
        {'Fwd time', 'Bwd time', 'Fwd mem', 'Bwd mem'} and values are
        speedup vs baseline (>1 = better than baseline).

    Baseline backend column is dropped (speedup is always 1.0).
    """
    metrics = [
        (FWD_MS_COL,  "Fwd time"),
        (BWD_MS_COL,  "Bwd time"),
        (FWD_MEM_COL, "Fwd mem"),
        (BWD_MEM_COL, "Bwd mem"),
        (MS_TOTAL, "Fwd + Bwd time")
    ]

    # decide index cols
    idx_cols = [CONV_COL, DATASET_COL, HEADS_COL, FEATURE_DIM_COL]

    metric_frames = []

    for metric, short_name in metrics:
        speed_col = f"{metric}_speedup_vs_{baseline}"
        if speed_col not in df_speed.columns:
            continue

        df_metric = df_speed[np.isfinite(df_speed[speed_col])].copy()
        if df_metric.empty:
            continue

        pivot = df_metric.pivot_table(
            index=idx_cols,
            columns=BACKEND_COL,
            values=speed_col,
            aggfunc="max",
        )

        # drop baseline backend (always 1.0)
        pivot = pivot.drop(columns=[baseline], errors="ignore")

        if pivot.empty:
            continue

        # attach metric name as top-level column
        pivot.columns = pd.MultiIndex.from_product(
            [[short_name], pivot.columns],
            names=["metric", "backend"],
        )

        metric_frames.append(pivot)

    if not metric_frames:
        return pd.DataFrame()

    table = pd.concat(metric_frames, axis=1)

    # sort rows & columns
    table = table.sort_index()
    table = table.sort_index(axis=1)

    return table
def build_raw_table_with_dataset_index(
    df: pd.DataFrame,
    index = None,
) -> pd.DataFrame:
    """
    Build a raw-metrics table with the same structure as
    `build_speedup_table_with_dataset_index`, but containing
    *raw* runtimes (ms) and memory (MB) for all backends.

    Index:
        (conv_type, dataset, heads, feature_dim)

    Columns:
        MultiIndex (metric_short, backend), where metric_short ∈
        {'Fwd time', 'Bwd time', 'Fwd mem', 'Bwd mem', 'Fwd + Bwd time'}.

    Values:
        Raw numbers from the corresponding metric columns.
    """
    metrics = [
        (FWD_MS_COL,  "Fwd time"),
        (BWD_MS_COL,  "Bwd time"),
        (FWD_MEM_COL, "Fwd mem"),
        (BWD_MEM_COL, "Bwd mem"),
        (MS_TOTAL,    "Fwd + Bwd time"),
    ]

    idx_cols = index or [CONV_COL, DATASET_COL, HEADS_COL, FEATURE_DIM_COL]

    metric_frames: list[pd.DataFrame] = []

    for metric, short_name in metrics:
        if metric not in df.columns:
            continue

        df_metric = df[np.isfinite(df[metric])].copy()
        if df_metric.empty:
            continue

        pivot = df_metric.pivot_table(
            index=idx_cols,
            columns=BACKEND_COL,
            values=metric,
            aggfunc="min",  # same choice as in speedup table
        )

        if pivot.empty:
            continue

        # put metric name on top level
        pivot.columns = pd.MultiIndex.from_product(
            [[short_name], pivot.columns],
            names=["metric", "backend"],
        )

        metric_frames.append(pivot)

    if not metric_frames:
        return pd.DataFrame()

    table = pd.concat(metric_frames, axis=1)

    table = table.sort_index()
    table = table.sort_index(axis=1)

    return table

In [29]:
no_reordering_df = df[df[REORDERING_COL] == -1]
[
    [
        CONV_COL,
        FWD_MS_COL,
        BWD_MS_COL,
        FWD_MEM_COL,
        BWD_MEM_COL,
        DATASET_COL,
        BACKEND_COL,
        HEADS_COL,
        FEATURE_DIM_COL,
        REORDERING_COL,
    ]
]
reordering_df = df[df[REORDERING_COL] != -1]

[
    [
        CONV_COL,
        FWD_MS_COL,
        BWD_MS_COL,
        FWD_MEM_COL,
        BWD_MEM_COL,
        DATASET_COL,
        BACKEND_COL,
        HEADS_COL,
        FEATURE_DIM_COL,
        REORDERING_COL,
    ]
]

[['conv_type',
  'forward_ms',
  'backward_ms',
  'forward_memory_mb',
  'backward_memory_mb',
  'dataset',
  'backend',
  'heads',
  'feature_dim',
  'graph_reordering_partition_size']]

In [30]:
datasets_df = df.groupby(DATASET_COL)[["num_nodes", "num_edges"]].max().reset_index()
datasets_df["density"] = datasets_df["num_edges"] / datasets_df["num_nodes"] / (datasets_df["num_nodes"] - 1)
datasets_df["average_node_degree"] = datasets_df["num_edges"] / datasets_df["num_nodes"]

datasets_df = datasets_df.sort_values(by="density", ascending=False).reset_index(drop=True)

In [31]:
datasets_df

          dataset  num_nodes  num_edges   density  average_node_degree
0       hm-prices      46563   21461990  0.009899           460.923695
1   hm-categories      46563   21461990  0.009899           460.923695
2      tolokers-2      11758    1038000  0.007509            88.280320
3       avazu-ctr      76269   21968154  0.003777           288.035165
4            cora       2708      10556  0.001440             3.898080
5        citeseer       3327       9104  0.000823             2.736399
6    twitch-views     168114   13595114  0.000481            80.868423
7          pubmed      19717      88648  0.000228             4.496019
8    artnet-views      50405     560696  0.000221            11.123817
9      artnet-exp      50405     560696  0.000221            11.123817
10   city-reviews     148801    2330830  0.000105            15.664075
11   city-roads-M      57073     132570  0.000041             2.322815
12     ogbn-arxiv     169343    1166243  0.000041             6.886869
13  ogbn-products    2449029  123718280  0.000021            50.517278
14   city-roads-L     142257     279061  0.000014             1.961668
15  pokec-regions    1632803   30622564  0.000011            18.754598
16      web-fraud    2890331   12895369  0.000002             4.461554
17     web-topics    2890331   12895369  0.000002             4.461554
18    web-traffic    2890331   12895369  0.000002             4.461554

In [32]:
datasets_df["dataset"].values.tolist()

['hm-prices',
 'hm-categories',
 'tolokers-2',
 'avazu-ctr',
 'cora',
 'citeseer',
 'twitch-views',
 'pubmed',
 'artnet-views',
 'artnet-exp',
 'city-reviews',
 'city-roads-M',
 'ogbn-arxiv',
 'ogbn-products',
 'city-roads-L',
 'pokec-regions',
 'web-fraud',
 'web-topics',
 'web-traffic']

In [33]:
px.box(df[(df[CONV_COL] == "gt") & (df[BACKEND_COL] != "dgl")], x=BACKEND_COL, y="ms_total_speedup_vs_dgl")

In [13]:
px.box(df[(df[CONV_COL] == "gt") & (df[BACKEND_COL] != "dgl")], x=BACKEND_COL, y="forward_ms_speedup_vs_dgl")

In [14]:
px.box(df[(df[CONV_COL] == "gcn") & (df[BACKEND_COL] != "dgl")], x=BACKEND_COL, y="forward_ms_speedup_vs_dgl")

In [15]:
px.box(df[(df[CONV_COL] == "gat_v2") & (df[BACKEND_COL] != "dgl")], x=BACKEND_COL, y="forward_ms_speedup_vs_dgl")

In [16]:
px.box(df[(df[CONV_COL] == "min_aggr") & (df[BACKEND_COL] != "dgl")], x=BACKEND_COL, y="forward_ms_speedup_vs_dgl")

## GT

In [17]:
no_reordering_df

,conv_type,dataset,backend,num_nodes,num_edges,avg_node_degree,feature_dim,forward_ms,forward_memory_mb,backward_ms,...,backward_ms_baseline_dgl,backward_ms_speedup_vs_dgl,forward_memory_mb_baseline_dgl,forward_memory_mb_speedup_vs_dgl,backward_memory_mb_baseline_dgl,backward_memory_mb_speedup_vs_dgl,ms_total_baseline_dgl,ms_total_speedup_vs_dgl,density,average_node_degree
0,gcn,artnet-exp,cusparse,50405,560696,0.089897,64,0.169984,44.418945,0.234086,...,0.413389,1.765967,91.189453,2.052941,118.342285,1.411166,1.647104,4.076280,0.000221,11.123817
1,gcn,artnet-exp,cusparse,50405,560696,0.089897,128,0.192717,71.554199,0.347750,...,0.469504,1.350118,140.412109,1.962318,192.176758,1.321805,1.635840,3.026715,0.000221,11.123817
2,gcn,artnet-exp,cusparse,50405,560696,0.089897,256,0.302285,122.330566,0.577331,...,0.677990,1.174353,241.964844,1.977959,344.090332,1.263502,1.849446,2.102561,0.000221,11.123817
3,gcn,artnet-exp,cusparse,50405,560696,0.089897,512,0.532480,219.225098,1.040486,...,1.121894,1.078240,435.753906,1.987701,634.773926,1.233608,2.592768,1.648330,0.000221,11.123817
4,gcn,artnet-exp,dgl,50405,560696,0.089897,64,1.233715,91.189453,0.413389,...,0.413389,1.000000,91.189453,1.000000,118.342285,1.000000,1.647104,1.000000,0.000221,11.123817
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,gt,pubmed,dfgnn,19717,88648,0.222419,256,1.082778,178.558594,2.828800,...,2.446131,0.864724,197.062012,1.103627,403.211426,1.194903,3.764429,0.962381,0.000228,4.496019
296,gt,pubmed,dfgnn,19717,88648,0.222419,256,1.173299,179.911133,2.823373,...,2.462106,0.872044,199.767090,1.110365,404.563965,1.194125,3.762586,0.941430,0.000228,4.496019
315,gt,pubmed,dfgnn,19717,88648,0.222419,512,2.279219,291.193848,4.914176,...,5.800448,1.180350,332.985840,1.143519,639.333008,1.056328,8.531456,1.186012,0.000228,4.496019
316,gt,pubmed,dfgnn,19717,88648,0.222419,512,2.288845,292.007324,4.909466,...,5.573018,1.135158,334.817383,1.146606,640.351074,1.056590,8.358912,1.161232,0.000228,4.496019
317,gt,pubmed,dfgnn,19717,88648,0.222419,512,2.323866,293.222656,4.916634,...,5.561139,1.131087,337.337891,1.150450,641.361816,1.056139,8.198349,1.132291,0.000228,4.496019

In [18]:
print(build_speedup_table_with_dataset_index(no_reordering_df[no_reordering_df[CONV_COL] == "gt"], "dgl").to_markdown(floatfmt=".2f"))

|                                 |   ('Bwd mem', 'cuda') |   ('Bwd mem', 'dfgnn') |   ('Bwd mem', 'triton_block_sparse') |   ('Bwd time', 'cuda') |   ('Bwd time', 'dfgnn') |   ('Bwd time', 'triton_block_sparse') |   ('Fwd + Bwd time', 'cuda') |   ('Fwd + Bwd time', 'dfgnn') |   ('Fwd + Bwd time', 'triton_block_sparse') |   ('Fwd mem', 'cuda') |   ('Fwd mem', 'dfgnn') |   ('Fwd mem', 'triton_block_sparse') |   ('Fwd time', 'cuda') |   ('Fwd time', 'dfgnn') |   ('Fwd time', 'triton_block_sparse') |
|:--------------------------------|----------------------:|-----------------------:|-------------------------------------:|-----------------------:|------------------------:|--------------------------------------:|-----------------------------:|------------------------------:|--------------------------------------------:|----------------------:|-----------------------:|-------------------------------------:|-----------------------:|------------------------:|--------------------------------------:|
| ('gt', 'artnet-exp', 2, 256)    |                  1.04 |                   1.03 |                                 1.19 |                   1.11 |                    1.15 |                                  0.63 |                         1.18 |                          1.16 |                                        0.77 |                  1.24 |                   1.20 |                                 1.07 |                   1.37 |                    1.18 |                                  1.38 |
| ('gt', 'artnet-exp', 2, 512)    |                  1.02 |                   1.08 |                                 1.20 |                   1.08 |                    1.14 |                                  0.60 |                         1.08 |                          1.15 |                                        0.73 |                  1.20 |                   1.19 |                                 1.07 |                   1.16 |                    1.15 |                                  1.28 |
| ('gt', 'artnet-exp', 4, 256)    |                  1.04 |                   1.03 |                                 1.20 |                   1.09 |                    1.13 |                                  0.71 |                         1.11 |                          1.14 |                                        0.84 |                  1.26 |                   1.20 |                                 1.10 |                   1.23 |                    1.17 |                                  1.30 |
| ('gt', 'artnet-exp', 4, 512)    |                  1.02 |                   1.08 |                                 1.21 |                   1.12 |                    1.19 |                                  0.76 |                         1.12 |                          1.19 |                                        0.88 |                  1.22 |                   1.19 |                                 1.08 |                   1.17 |                    1.19 |                                  1.28 |
| ('gt', 'artnet-exp', 8, 256)    |                  1.05 |                   1.03 |                                 1.21 |                   1.05 |                    1.17 |                                  0.81 |                         1.03 |                          1.18 |                                        0.96 |                  1.31 |                   1.22 |                                 1.14 |                   1.21 |                    1.20 |                                  1.46 |
| ('gt', 'artnet-exp', 8, 512)    |                  1.03 |                   1.08 |                                 1.21 |                   1.10 |                    1.21 |                                  0.78 |                         1.05 |                          1.21 |                                        0.89 |                  1.24 |                   1.20 |                                 1.11 |                   1.11 |                    1.20 |                                  1.25 |
| ('gt', 'artnet-views', 2, 256)  |                  1.04 |                   1.03 |                                 1.20 |                   1.12 |                    1.24 |                                  0.63 |                         1.18 |                          1.21 |                                        0.77 |                  1.22 |                   1.17 |                                 1.06 |                   1.36 |                    1.15 |                                  1.37 |
| ('gt', 'artnet-views', 2, 512)  |                  1.02 |                   1.08 |                                 1.20 |                   1.08 |                    1.17 |                                  0.60 |                         1.08 |                          1.13 |                                        0.72 |                  1.20 |                   1.19 |                                 1.07 |                   1.16 |                    1.07 |                                  1.28 |
| ('gt', 'artnet-views', 4, 256)  |                  1.04 |                   1.03 |                                 1.20 |                   1.19 |                    1.25 |                                  0.73 |                         1.12 |                          1.26 |                                        0.86 |                  1.27 |                   1.21 |                                 1.10 |                   1.23 |                    1.29 |                                  1.31 |
| ('gt', 'artnet-views', 4, 512)  |                  1.02 |                   1.08 |                                 1.21 |                   1.12 |                    1.19 |                                  0.76 |                         1.12 |                          1.19 |                                        0.87 |                  1.22 |                   1.19 |                                 1.09 |                   1.17 |                    1.19 |                                  1.28 |
| ('gt', 'artnet-views', 8, 256)  |                  1.05 |                   1.03 |                                 1.21 |                   1.05 |                    1.03 |                                  0.82 |                         1.03 |                          1.09 |                                        0.98 |                  1.32 |                   1.22 |                                 1.14 |                   1.21 |                    1.24 |                                  1.47 |
| ('gt', 'artnet-views', 8, 512)  |                  1.03 |                   1.08 |                                 1.21 |                   1.10 |                    1.22 |                                  0.78 |                         1.05 |                          1.11 |                                        0.89 |                  1.24 |                   1.20 |                                 1.11 |                   1.11 |                    0.94 |                                  1.26 |
| ('gt', 'avazu-ctr', 2, 256)     |                  2.00 |                 nan    |                                 1.46 |                   0.85 |                  nan    |                                  0.74 |                         1.11 |                        nan    |                                        1.15 |                  2.31 |                 nan    |                                 1.16 |                   2.68 |                  nan    |                                  4.76 |
| ('gt', 'avazu-ctr', 2, 512)     |                  1.43 |                 nan    |                                 1.27 |                   0.72 |                  nan    |                                  0.49 |                         0.90 |                        nan    |                                        0.74 |                  2.14 |                 nan    |                                 1.31 |                   2.16 |                  nan    |                                  4.35 |
| ('gt', 'avazu-ctr', 4, 256)     |                  2.64 |                 nan    |                                 1.93 |                   0.87 |                  nan    |                                  0.96 |                         1.14 |                        nan    |                                        1.47 |                  3.49 |                 nan    |                                 1.76 |                   2.76 |                  nan    |                                  4.76 |
| ('gt', 'avazu-ctr', 4, 512)     |                  1.75 |                 nan    |                                 1.56 |                   0.91 |                  nan    |                                  0.74 |                         1.11 |                        nan    |                                        1.10 |                  2.47 |                 nan    |                                 1.51 |                   2.46 |                  nan    |                                  4.30 |
| ('gt', 'avazu-ctr', 8, 256)     |                  3.92 |                 nan    |                                 2.87 |                   0.86 |                  nan    |                                  1.33 |                         1.18 |                        nan    |                                        1.95 |                  4.90 |                 nan    |                                 2.47 |                   3.50 |                  nan    |                                  4.54 |
| ('gt', 'avazu-ctr', 8, 512)     |                  2.46 |                 nan    |                                 2.19 |                   0.92 |                  nan    |                                  0.94 |                         1.12 |                        nan    |                                        1.36 |                  3.33 |                 nan    |                                 2.03 |                   2.43 |                  nan    |                                  3.96 |
| ('gt', 'citeseer', 2, 256)      |                  1.01 |                   1.12 |                                 1.08 |                   2.42 |                    1.17 |                                  1.78 |                         3.13 |                          1.54 |                                        1.87 |                  1.05 |                   1.04 |                                 1.03 |                   4.58 |                    2.35 |                                  1.97 |
| ('gt', 'citeseer', 2, 512)      |                  1.01 |                   1.18 |                                 1.10 |                   1.58 |                    1.57 |                                  1.23 |                         1.85 |                          1.69 |                                        1.57 |                  1.07 |                   1.06 |                                 1.03 |                   2.45 |                    1.90 |                                  2.67 |
| ('gt', 'citeseer', 4, 256)      |                  1.01 |                   1.12 |                                 1.08 |                   2.36 |                    1.24 |                                  1.97 |                         3.08 |                          1.56 |                                        2.27 |                  1.05 |                   1.04 |                                 1.03 |                   4.57 |                    2.16 |                                  2.69 |
| ('gt', 'citeseer', 4, 512)      |                  1.01 |                   1.18 |                                 1.10 |                   1.65 |                    1.64 |                                  1.38 |                         1.89 |                          1.81 |                                        1.72 |                  1.07 |                   1.06 |                                 1.03 |                   2.41 |                    2.13 |                                  2.66 |
| ('gt', 'citeseer', 8, 256)      |                  1.01 |                   1.12 |                                 1.08 |                   2.23 |                    1.04 |                                  2.08 |                         2.95 |                          1.37 |                                        2.34 |                  1.05 |                   1.04 |                                 1.03 |                   4.48 |                    2.08 |                                  2.69 |
| ('gt', 'citeseer', 8, 512)      |                  1.01 |                   1.18 |                                 1.10 |                   1.66 |                    1.73 |                                  1.49 |                         1.87 |                          1.87 |                                        1.81 |                  1.07 |                   1.06 |                                 1.03 |                   2.28 |                    2.15 |                                  2.64 |
| ('gt', 'city-reviews', 2, 256)  |                  1.05 |                 nan    |                                 1.18 |                   0.89 |                  nan    |                                  0.53 |                         0.99 |                        nan    |                                        0.71 |                  1.23 |                 nan    |                                 1.03 |                   1.48 |                  nan    |                                  1.71 |
| ('gt', 'city-reviews', 2, 512)  |                  1.03 |                 nan    |                                 1.20 |                   0.88 |                  nan    |                                  0.49 |                         0.92 |                        nan    |                                        0.63 |                  1.22 |                 nan    |                                 1.07 |                   1.20 |                  nan    |                                  1.46 |
| ('gt', 'city-reviews', 4, 256)  |                  1.06 |                 nan    |                                 1.19 |                   0.92 |                  nan    |                                  0.64 |                         1.00 |                        nan    |                                        0.85 |                  1.30 |                 nan    |                                 1.09 |                   1.52 |                  nan    |                                  1.82 |
| ('gt', 'city-reviews', 4, 512)  |                  1.03 |                 nan    |                                 1.20 |                   1.00 |                  nan    |                                  0.66 |                         1.02 |                        nan    |                                        0.81 |                  1.24 |                 nan    |                                 1.08 |                   1.30 |                  nan    |                                  1.50 |
| ('gt', 'city-reviews', 8, 256)  |                  1.07 |                 nan    |                                 1.21 |                   0.84 |                  nan    |                                  0.80 |                         0.97 |                        nan    |                                        1.02 |                  1.36 |                 nan    |                                 1.15 |                   1.63 |                  nan    |                                  1.78 |
| ('gt', 'city-reviews', 8, 512)  |                  1.04 |                 nan    |                                 1.21 |                   1.00 |                  nan    |                                  0.71 |                         1.00 |                        nan    |                                        0.86 |                  1.27 |                 nan    |                                 1.12 |                   1.27 |                  nan    |                                  1.42 |
| ('gt', 'city-roads-L', 2, 256)  |                  1.01 |                   1.09 |                                 1.20 |                   1.16 |                    1.05 |                                  0.95 |                         1.15 |                          1.03 |                                        1.01 |                  1.15 |                   1.15 |                                 1.06 |                   1.13 |                    0.97 |                                  1.18 |
| ('gt', 'city-roads-L', 2, 512)  |                  1.00 |                   1.13 |                                 1.21 |                   1.13 |                    1.08 |                                  1.00 |                         1.13 |                          1.10 |                                        1.04 |                  1.16 |                   1.16 |                                 1.07 |                   1.15 |                    1.12 |                                  1.15 |
| ('gt', 'city-roads-L', 4, 256)  |                  1.01 |                   1.09 |                                 1.20 |                   1.21 |                    0.97 |                                  0.86 |                         1.13 |                          0.96 |                                        0.94 |                  1.16 |                   1.16 |                                 1.07 |                   1.01 |                    0.92 |                                  1.18 |
| ('gt', 'city-roads-L', 4, 512)  |                  1.00 |                   1.13 |                                 1.21 |                   1.13 |                    1.11 |                                  1.01 |                         1.13 |                          1.11 |                                        1.05 |                  1.16 |                   1.16 |                                 1.07 |                   1.14 |                    1.12 |                                  1.15 |
| ('gt', 'city-roads-L', 8, 256)  |                  1.01 |                   1.09 |                                 1.20 |                   1.07 |                    1.07 |                                  0.83 |                         1.01 |                          0.92 |                                        0.94 |                  1.17 |                   1.16 |                                 1.08 |                   0.92 |                    0.72 |                                  1.30 |
| ('gt', 'city-roads-L', 8, 512)  |                  1.00 |                   1.13 |                                 1.21 |                   1.12 |                    1.14 |                                  0.91 |                         1.10 |                          1.13 |                                        0.97 |                  1.17 |                   1.16 |                                 1.08 |                   1.06 |                    1.10 |                                  1.15 |
| ('gt', 'city-roads-M', 2, 256)  |                  1.00 |                   1.01 |                                 1.20 |                   1.18 |                    1.16 |                                  0.90 |                         1.17 |                          1.10 |                                        0.98 |                  1.16 |                   1.15 |                                 1.07 |                   1.14 |                    1.00 |                                  1.20 |

In [19]:
print(build_raw_table_with_dataset_index(no_reordering_df[no_reordering_df[CONV_COL] == "gt"]).to_markdown(floatfmt=".2f"))

|                                 |   ('Bwd mem', 'cuda') |   ('Bwd mem', 'dfgnn') |   ('Bwd mem', 'dgl') |   ('Bwd mem', 'triton_block_sparse') |   ('Bwd time', 'cuda') |   ('Bwd time', 'dfgnn') |   ('Bwd time', 'dgl') |   ('Bwd time', 'triton_block_sparse') |   ('Fwd + Bwd time', 'cuda') |   ('Fwd + Bwd time', 'dfgnn') |   ('Fwd + Bwd time', 'dgl') |   ('Fwd + Bwd time', 'triton_block_sparse') |   ('Fwd mem', 'cuda') |   ('Fwd mem', 'dfgnn') |   ('Fwd mem', 'dgl') |   ('Fwd mem', 'triton_block_sparse') |   ('Fwd time', 'cuda') |   ('Fwd time', 'dfgnn') |   ('Fwd time', 'dgl') |   ('Fwd time', 'triton_block_sparse') |
|:--------------------------------|----------------------:|-----------------------:|---------------------:|-------------------------------------:|-----------------------:|------------------------:|----------------------:|--------------------------------------:|-----------------------------:|------------------------------:|----------------------------:|--------------------------------------------:|----------------------:|-----------------------:|---------------------:|-------------------------------------:|-----------------------:|------------------------:|----------------------:|--------------------------------------:|
| ('gt', 'artnet-exp', 2, 256)    |                742.73 |                 746.43 |               768.78 |                               644.58 |                   4.97 |                    4.81 |                  5.52 |                                  8.70 |                         7.05 |                          7.16 |                        8.28 |                                       10.71 |                328.75 |                 339.57 |               406.42 |                               378.50 |                   2.01 |                    2.35 |                  2.76 |                                  2.01 |
| ('gt', 'artnet-exp', 2, 512)    |               1422.83 |                1343.33 |              1448.89 |                              1205.06 |                  13.84 |                   13.02 |                 14.89 |                                 24.64 |                        20.15 |                         19.02 |                       21.81 |                                       30.06 |                631.59 |                 640.63 |               760.38 |                               709.16 |                   5.97 |                    6.00 |                  6.92 |                                  5.42 |
| ('gt', 'artnet-exp', 4, 256)    |                743.11 |                 750.70 |               773.06 |                               644.19 |                   5.27 |                    5.07 |                  5.73 |                                  8.13 |                         7.80 |                          7.58 |                        8.68 |                                       10.39 |                335.60 |                 351.98 |               424.11 |                               386.23 |                   2.39 |                    2.51 |                  2.95 |                                  2.26 |
| ('gt', 'artnet-exp', 4, 512)    |               1423.22 |                1347.60 |              1453.17 |                              1204.67 |                  13.58 |                   12.71 |                 15.14 |                                 19.87 |                        19.99 |                         18.74 |                       22.30 |                                       25.47 |                631.98 |                 644.91 |               768.93 |                               708.77 |                   6.10 |                    6.03 |                  7.16 |                                  5.60 |
| ('gt', 'artnet-exp', 8, 256)    |                743.88 |                 760.15 |               781.61 |                               645.00 |                   6.09 |                    5.48 |                  6.42 |                                  7.91 |                         9.65 |                          8.46 |                        9.99 |                                       10.36 |                336.37 |                 361.42 |               441.22 |                               387.04 |                   2.95 |                    2.98 |                  3.58 |                                  2.45 |
| ('gt', 'artnet-exp', 8, 512)    |               1424.00 |                1357.05 |              1461.72 |                              1205.45 |                  14.16 |                   12.88 |                 15.64 |                                 20.13 |                        22.21 |                         19.18 |                       23.23 |                                       26.19 |                632.76 |                 654.36 |               786.04 |                               709.55 |                   6.85 |                    6.30 |                  7.58 |                                  6.06 |
| ('gt', 'artnet-views', 2, 256)  |                737.50 |                 741.62 |               763.78 |                               637.74 |                   4.95 |                    4.44 |                  5.53 |                                  8.73 |                         7.01 |                          6.83 |                        8.26 |                                       10.73 |                330.00 |                 342.89 |               401.61 |                               380.23 |                   2.01 |                    2.38 |                  2.74 |                                  1.99 |
| ('gt', 'artnet-views', 2, 512)  |               1418.36 |                1338.52 |              1443.89 |                              1199.00 |                  13.82 |                   12.79 |                 14.90 |                                 24.75 |                        20.12 |                         19.27 |                       21.82 |                                       30.15 |                627.12 |                 635.83 |               755.38 |                               703.10 |                   5.97 |                    6.49 |                  6.92 |                                  5.40 |
| ('gt', 'artnet-views', 4, 256)  |                737.89 |                 745.90 |               768.06 |                               638.12 |                   4.81 |                    4.58 |                  5.73 |                                  7.90 |                         7.78 |                          6.86 |                        8.68 |                                       10.14 |                330.38 |                 347.17 |               419.11 |                               380.62 |                   2.39 |                    2.28 |                  2.95 |                                  2.25 |
| ('gt', 'artnet-views', 4, 512)  |               1417.99 |                1342.80 |              1448.16 |                              1199.38 |                  13.54 |                   12.67 |                 15.13 |                                 19.96 |                        19.96 |                         18.67 |                       22.29 |                                       25.54 |                626.75 |                 640.10 |               763.93 |                               703.48 |                   6.10 |                    6.00 |                  7.16 |                                  5.58 |
| ('gt', 'artnet-views', 8, 256)  |                738.66 |                 755.34 |               776.61 |                               639.49 |                   6.07 |                    6.23 |                  6.39 |                                  7.75 |                         9.63 |                          9.12 |                        9.97 |                                       10.19 |                331.15 |                 356.61 |               436.22 |                               381.99 |                   2.95 |                    2.89 |                  3.58 |                                  2.43 |
| ('gt', 'artnet-views', 8, 512)  |               1419.83 |                1352.24 |              1456.72 |                              1200.75 |                  14.15 |                   12.83 |                 15.62 |                                 20.05 |                        22.17 |                         20.89 |                       23.22 |                                       26.09 |                627.96 |                 649.55 |               781.04 |                               704.85 |                   6.86 |                    8.06 |                  7.60 |                                  6.04 |
| ('gt', 'avazu-ctr', 2, 256)     |               1308.09 |                 nan    |              2614.23 |                              1787.69 |                  92.50 |                  nan    |                 78.97 |                                107.39 |                       124.52 |                        nan    |                      138.22 |                                      119.84 |                710.93 |                 nan    |              1644.74 |                              1413.98 |                  22.10 |                  nan    |                 59.26 |                                 12.45 |
| ('gt', 'avazu-ctr', 2, 512)     |               2354.98 |                 nan    |              3361.54 |                              2646.86 |                 190.31 |                  nan    |                136.50 |                                279.37 |                       246.54 |                        nan    |                      221.60 |                                      298.92 |               1159.67 |                 nan    |              2483.80 |                              1899.04 |                  39.38 |                  nan    |                 85.11 |                                 19.55 |
| ('gt', 'avazu-ctr', 4, 256)     |               1308.85 |                 nan    |              3455.62 |                              1788.29 |                 101.89 |                  nan    |                 88.64 |                                 92.43 |                       137.51 |                        nan    |                      157.34 |                                      106.87 |                711.69 |                 nan    |              2486.46 |                              1414.57 |                  24.92 |                  nan    |                 68.70 |                                 14.44 |
| ('gt', 'avazu-ctr', 4, 512)     |               2354.98 |                 nan    |              4129.90 |                              2647.46 |                 163.09 |                  nan    |                147.69 |                                199.02 |                       218.04 |                        nan    |                      242.73 |                                      221.10 |               1160.27 |                 nan    |              2860.74 |                              1899.64 |                  38.59 |                  nan    |                 95.04 |                                 22.08 |
| ('gt', 'avazu-ctr', 8, 256)     |               1309.84 |                 nan    |              5128.84 |                              1789.44 |                 130.56 |                  nan    |                112.54 |                                 84.78 |                       173.51 |                        nan    |                      204.98 |                                      105.15 |                712.68 |                 nan    |              3491.66 |                              1415.72 |                  26.39 |                  nan    |                 92.44 |                                 20.37 |
| ('gt', 'avazu-ctr', 8, 512)     |               2357.61 |                 nan    |              5803.13 |                              2649.28 |                 180.33 |                  nan    |                166.57 |                                177.16 |                       250.30 |                        nan    |                      279.22 |                                      205.60 |               1162.15 |                 nan    |              3866.44 |                              1901.46 |                  46.41 |                  nan    |                112.65 |                                 28.44 |
| ('gt', 'citeseer', 2, 256)      |                124.19 |                 112.28 |               126.05 |                               116.54 |                   0.54 |                    1.12 |                  1.31 |                                  0.73 |                         0.81 |                          1.64 |                        2.53 |                                        1.35 |                 83.69 |                  84.77 |                88.20 |                                85.78 |                   0.27 |                    0.52 |                  1.22 |                                  0.62 |
| ('gt', 'citeseer', 2, 512)      |                190.61 |                 162.58 |               191.58 |                               173.66 |                   1.12 |                    1.13 |                  1.77 |                                  1.44 |                         1.62 |                          1.77 |                        2.99 |                                        1.90 |                105.44 |                 106.08 |               112.42 |                               109.15 |                   0.50 |                    0.64 |                  1.22 |                                  0.46 |
| ('gt', 'citeseer', 4, 256)      |                124.72 |                 112.35 |               125.61 |                               116.56 |                   0.55 |                    1.05 |                  1.30 |                                  0.66 |                         0.82 |                          1.62 |                        2.52 |                                        1.11 |                 84.22 |                  84.84 |                88.50 |                                85.81 |                   0.27 |                    0.57 |                  1.22 |                                  0.45 |
| ('gt', 'citeseer', 4, 512)      |                190.64 |                 162.65 |               191.65 |                               173.69 |                   1.08 |                    1.08 |                  1.77 |                                  1.28 |                         1.58 |                          1.65 |                        3.00 |                                        1.75 |                105.46 |                 106.15 |               112.56 |                               109.18 |                   0.51 |                    0.58 |                  1.23 |                                  0.46 |
| ('gt', 'citeseer', 8, 256)      |                124.77 |                 112.49 |               125.75 |                               116.61 |                   0.58 |                    1.25 |                  1.30 |                                  0.62 |                         0.86 |                          1.84 |                        2.52 |                                        1.08 |                 84.27 |                  84.98 |                88.78 |                                85.86 |                   0.27 |                    0.59 |                  1.22 |                                  0.46 |
| ('gt', 'citeseer', 8, 512)      |                190.69 |                 162.79 |               191.79 |                               173.74 |                   1.10 |                    1.06 |                  1.83 |                                  1.23 |                         1.63 |                          1.63 |                        3.05 |                                        1.69 |                105.51 |                 106.29 |               112.83 |                               109.23 |                   0.53 |                    0.57 |                  1.22 |                                  0.46 |
| ('gt', 'city-reviews', 2, 256)  |               2196.43 |                 nan    |              2304.00 |                              1949.89 |                  22.14 |                  nan    |                 19.70 |                                 37.20 |                        31.37 |                        nan    |                       31.12 |                                       43.89 |               1030.37 |                 nan    |              1264.33 |                              1221.83 |                   7.73 |                  nan    |                 11.42 |                                  6.68 |
| ('gt', 'city-reviews', 2, 512)  |               4230.88 |                 nan    |              4337.52 |                              3625.65 |                  56.78 |                  nan    |                 49.71 |                                100.70 |                        81.38 |                        nan    |                       74.55 |                                      117.67 |               1902.74 |                 nan    |              2317.80 |                              2169.39 |                  20.71 |                  nan    |                 24.84 |                                 16.97 |
| ('gt', 'city-reviews', 4, 256)  |               2197.57 |                 nan    |              2321.79 |                              1950.82 |                  22.82 |                  nan    |                 21.06 |                                 32.89 |                        34.31 |                        nan    |                       34.28 |                                       40.14 |               1031.50 |                 nan    |              1336.60 |                              1222.75 |                   8.68 |                  nan    |                 13.23 |                                  7.25 |
| ('gt', 'city-reviews', 4, 512)  |               4232.51 |                 nan    |              4355.81 |                              3627.28 |                  50.90 |                  nan    |                 51.14 |                                 77.94 |                        76.15 |                        nan    |                       77.83 |                                       95.73 |               1903.64 |                 nan    |              2353.87 |                              2171.02 |                  20.50 |                  nan    |                 26.69 |                                 17.79 |
| ('gt', 'city-reviews', 8, 256)  |               2199.84 |                 nan    |              2357.35 |                              1953.49 |                  28.43 |                  nan    |                 23.96 |                                 30.04 |                        41.13 |                        nan    |                       40.07 |                                       39.11 |               1033.77 |                 nan    |              1407.73 |                              1225.42 |                   9.90 |                  nan    |                 16.11 |                                  9.07 |

In [20]:
print(build_raw_table_with_dataset_index(df[df[CONV_COL] == "gt"], [CONV_COL, DATASET_COL, HEADS_COL, FEATURE_DIM_COL, REORDERING_COL]).to_markdown(floatfmt=".2f"))

|                                       |   ('Bwd mem', 'cuda') |   ('Bwd mem', 'dfgnn') |   ('Bwd mem', 'dgl') |   ('Bwd mem', 'triton_block_sparse') |   ('Bwd time', 'cuda') |   ('Bwd time', 'dfgnn') |   ('Bwd time', 'dgl') |   ('Bwd time', 'triton_block_sparse') |   ('Fwd + Bwd time', 'cuda') |   ('Fwd + Bwd time', 'dfgnn') |   ('Fwd + Bwd time', 'dgl') |   ('Fwd + Bwd time', 'triton_block_sparse') |   ('Fwd mem', 'cuda') |   ('Fwd mem', 'dfgnn') |   ('Fwd mem', 'dgl') |   ('Fwd mem', 'triton_block_sparse') |   ('Fwd time', 'cuda') |   ('Fwd time', 'dfgnn') |   ('Fwd time', 'dgl') |   ('Fwd time', 'triton_block_sparse') |
|:--------------------------------------|----------------------:|-----------------------:|---------------------:|-------------------------------------:|-----------------------:|------------------------:|----------------------:|--------------------------------------:|-----------------------------:|------------------------------:|----------------------------:|--------------------------------------------:|----------------------:|-----------------------:|---------------------:|-------------------------------------:|-----------------------:|------------------------:|----------------------:|--------------------------------------:|
| ('gt', 'artnet-exp', 2, 256, -1)      |                742.73 |                 746.43 |               768.78 |                               644.58 |                   4.97 |                    4.81 |                  5.52 |                                  8.70 |                         7.05 |                          7.16 |                        8.28 |                                       10.71 |                328.75 |                 339.57 |               406.42 |                               378.50 |                   2.01 |                    2.35 |                  2.76 |                                  2.01 |
| ('gt', 'artnet-exp', 2, 256, 128)     |                741.92 |                 746.43 |               767.08 |                               643.47 |                   4.96 |                    4.66 |                  5.51 |                                  9.04 |                         7.46 |                          6.85 |                        8.22 |                                       11.05 |                334.42 |                 347.70 |               404.91 |                               379.30 |                   2.50 |                    2.19 |                  2.71 |                                  2.01 |
| ('gt', 'artnet-exp', 2, 256, 512)     |                741.92 |                 746.43 |               767.08 |                               643.47 |                   4.96 |                    4.62 |                  5.59 |                                  8.51 |                         7.46 |                          6.77 |                        8.30 |                                       10.50 |                334.42 |                 347.70 |               404.91 |                               385.52 |                   2.50 |                    2.15 |                  2.71 |                                  1.99 |
| ('gt', 'artnet-exp', 2, 256, 1024)    |                741.92 |                 746.43 |               767.08 |                               643.47 |                   4.98 |                    5.03 |                  5.52 |                                  8.30 |                         7.52 |                          7.44 |                        8.24 |                                       10.28 |                334.42 |                 347.70 |               404.91 |                               385.52 |                   2.55 |                    2.41 |                  2.73 |                                  1.98 |
| ('gt', 'artnet-exp', 2, 256, 2048)    |                741.92 |                 746.43 |               767.08 |                               643.47 |                   4.96 |                    5.23 |                  5.58 |                                  8.57 |                         7.46 |                          9.49 |                        8.31 |                                       10.59 |                334.42 |                 347.70 |               404.91 |                               385.52 |                   2.50 |                    4.26 |                  2.73 |                                  2.00 |
| ('gt', 'artnet-exp', 2, 256, 4096)    |                741.92 |                 746.43 |               767.08 |                               643.47 |                   4.97 |                    4.87 |                  5.51 |                                  8.34 |                         7.47 |                          7.22 |                        8.27 |                                       10.34 |                334.42 |                 347.70 |               404.91 |                               385.52 |                   2.50 |                    2.36 |                  2.74 |                                  1.99 |
| ('gt', 'artnet-exp', 2, 256, 8192)    |                741.92 |                 746.43 |               767.08 |                               643.47 |                   4.96 |                    5.01 |                  5.51 |                                  8.47 |                         7.46 |                          7.42 |                        8.22 |                                       10.46 |                334.42 |                 347.70 |               404.91 |                               385.52 |                   2.51 |                    2.41 |                  2.72 |                                  1.99 |
| ('gt', 'artnet-exp', 2, 512, -1)      |               1422.83 |                1343.33 |              1448.89 |                              1205.06 |                  13.84 |                   13.02 |                 14.89 |                                 24.64 |                        20.15 |                         19.02 |                       21.81 |                                       30.06 |                631.59 |                 640.63 |               760.38 |                               709.16 |                   5.97 |                    6.00 |                  6.92 |                                  5.42 |
| ('gt', 'artnet-exp', 2, 512, 128)     |               1422.83 |                1343.33 |              1448.28 |                              1203.96 |                  13.71 |                   12.78 |                 14.88 |                                 25.21 |                        20.09 |                         18.82 |                       21.80 |                                       30.63 |                631.56 |                 640.63 |               759.77 |                               708.06 |                   6.32 |                    6.03 |                  6.92 |                                  5.42 |
| ('gt', 'artnet-exp', 2, 512, 512)     |               1422.83 |                1343.33 |              1448.28 |                              1203.96 |                  13.83 |                   12.87 |                 14.87 |                                 24.54 |                        20.14 |                         18.88 |                       21.78 |                                       29.89 |                631.56 |                 640.63 |               759.77 |                               708.06 |                   6.31 |                    6.01 |                  6.91 |                                  5.35 |
| ('gt', 'artnet-exp', 2, 512, 1024)    |               1422.83 |                1343.33 |              1448.28 |                              1203.96 |                  13.77 |                   13.23 |                 14.94 |                                 24.50 |                        20.11 |                         19.27 |                       21.89 |                                       29.90 |                631.56 |                 640.63 |               759.77 |                               708.06 |                   6.33 |                    6.04 |                  6.91 |                                  5.40 |
| ('gt', 'artnet-exp', 2, 512, 2048)    |               1422.83 |                1343.33 |              1448.28 |                              1203.96 |                  13.71 |                   14.41 |                 14.87 |                                 24.15 |                        20.10 |                         20.44 |                       21.78 |                                       29.57 |                631.56 |                 640.63 |               759.77 |                               708.06 |                   6.31 |                    6.03 |                  6.91 |                                  5.40 |
| ('gt', 'artnet-exp', 2, 512, 4096)    |               1422.83 |                1343.33 |              1448.28 |                              1203.96 |                  13.74 |                   12.84 |                 14.91 |                                 24.48 |                        20.18 |                         18.87 |                       21.85 |                                       29.87 |                631.56 |                 640.63 |               759.77 |                               708.06 |                   6.33 |                    6.03 |                  6.93 |                                  5.39 |
| ('gt', 'artnet-exp', 2, 512, 8192)    |               1422.83 |                1343.33 |              1448.28 |                              1203.96 |                  13.73 |                   12.96 |                 14.88 |                                 23.83 |                        20.15 |                         19.02 |                       21.79 |                                       29.25 |                631.56 |                 640.63 |               759.77 |                               708.06 |                   6.31 |                    6.06 |                  6.91 |                                  5.40 |
| ('gt', 'artnet-exp', 4, 256, -1)      |                743.11 |                 750.70 |               773.06 |                               644.19 |                   5.27 |                    5.07 |                  5.73 |                                  8.13 |                         7.80 |                          7.58 |                        8.68 |                                       10.39 |                335.60 |                 351.98 |               424.11 |                               386.23 |                   2.39 |                    2.51 |                  2.95 |                                  2.26 |
| ('gt', 'artnet-exp', 4, 256, 128)     |                742.31 |                 750.70 |               771.36 |                               643.86 |                   4.87 |                    4.74 |                  5.72 |                                  8.19 |                         8.10 |                          7.11 |                        8.66 |                                       10.50 |                334.80 |                 351.98 |               422.41 |                               385.90 |                   3.22 |                    2.37 |                  2.94 |                                  2.22 |
| ('gt', 'artnet-exp', 4, 256, 512)     |                742.31 |                 750.70 |               771.36 |                               643.86 |                   5.00 |                    5.03 |                  5.76 |                                  7.49 |                         8.29 |                          7.65 |                        8.71 |                                        9.70 |                334.80 |                 351.98 |               422.41 |                               385.90 |                   3.25 |                    2.61 |                  2.95 |                                  2.21 |
| ('gt', 'artnet-exp', 4, 256, 1024)    |                742.31 |                 750.70 |               771.36 |                               643.86 |                   5.07 |                    4.64 |                  5.73 |                                  7.50 |                         8.26 |                          7.26 |                        8.69 |                                        9.54 |                334.80 |                 351.98 |               422.41 |                               385.90 |                   3.20 |                    2.61 |                  2.96 |                                  2.03 |
| ('gt', 'artnet-exp', 4, 256, 2048)    |                742.31 |                 750.70 |               771.36 |                               643.86 |                   4.86 |                    5.01 |                  5.81 |                                  7.62 |                         7.99 |                          7.65 |                        8.80 |                                        9.85 |                334.80 |                 351.98 |               422.41 |                               385.90 |                   3.13 |                    2.64 |                  2.98 |                                  2.08 |
| ('gt', 'artnet-exp', 4, 256, 4096)    |                742.31 |                 750.70 |               771.36 |                               643.86 |                   4.83 |                    4.76 |                  5.73 |                                  8.00 |                         8.18 |                         10.41 |                        8.67 |                                       10.12 |                334.80 |                 351.98 |               422.41 |                               385.90 |                   3.27 |                    5.65 |                  2.94 |                                  2.12 |
| ('gt', 'artnet-exp', 4, 256, 8192)    |                742.31 |                 750.70 |               771.36 |                               643.86 |                   5.16 |                    5.15 |                  5.75 |                                  7.51 |                         8.60 |                          7.82 |                        8.70 |                                        9.56 |                334.80 |                 351.98 |               422.41 |                               385.90 |                   3.38 |                    2.67 |                  2.95 |                                  2.05 |
| ('gt', 'artnet-exp', 4, 512, -1)      |               1423.22 |                1347.60 |              1453.17 |                              1204.67 |                  13.58 |                   12.71 |                 15.14 |                                 19.87 |                        19.99 |                         18.74 |                       22.30 |                                       25.47 |                631.98 |                 644.91 |               768.93 |                               708.77 |                   6.10 |                    6.03 |                  7.16 |                                  5.60 |
| ('gt', 'artnet-exp', 4, 512, 128)     |               1423.19 |                1347.60 |              1452.55 |                              1204.34 |                  13.51 |                   12.77 |                 15.26 |                                 19.76 |                        19.95 |                         18.85 |                       22.43 |                                       25.37 |                631.95 |                 644.91 |               768.01 |                               708.44 |                   6.41 |                    6.08 |                  7.16 |                                  5.61 |
| ('gt', 'artnet-exp', 4, 512, 512)     |               1423.19 |                1347.60 |              1452.55 |                              1204.34 |                  13.52 |                   12.65 |                 15.13 |                                 19.76 |                        19.94 |                         18.72 |                       22.29 |                                       25.31 |                631.95 |                 644.91 |               768.01 |                               708.44 |                   6.41 |                    6.07 |                  7.15 |                                  5.55 |
| ('gt', 'artnet-exp', 4, 512, 1024)    |               1423.19 |                1347.60 |              1452.55 |                              1204.34 |                  13.77 |                   13.10 |                 15.13 |                                 19.67 |                        20.25 |                         19.31 |                       22.28 |                                       25.22 |                631.95 |                 644.91 |               768.01 |                               708.44 |                   6.43 |                    6.21 |                  7.15 |                                  5.55 |
| ('gt', 'artnet-exp', 4, 512, 2048)    |               1423.19 |                1347.60 |              1452.55 |                              1204.34 |                  13.46 |                   12.60 |                 15.11 |                                 19.79 |                        19.97 |                         18.66 |                       22.27 |                                       25.38 |                631.95 |                 644.91 |               768.01 |                               708.44 |                   6.41 |                    6.05 |                  7.16 |                                  5.57 |
| ('gt', 'artnet-exp', 4, 512, 4096)    |               1423.19 |                1347.60 |              1452.55 |                              1204.34 |                  13.43 |                   12.74 |                 15.12 |                                 19.72 |                        19.94 |                         18.78 |                       22.28 |                                       25.27 |                631.95 |                 644.91 |               768.01 |                               708.44 |                   6.41 |                    6.04 |                  7.16 |                                  5.55 |
| ('gt', 'artnet-exp', 4, 512, 8192)    |               1423.19 |                1347.60 |              1452.55 |                              1204.34 |                  13.42 |                   13.01 |                 15.12 |                                 19.73 |                        19.88 |                         19.05 |                       22.28 |                                       25.28 |                631.95 |                 644.91 |               768.01 |                               708.44 |                   6.41 |                    6.04 |                  7.16 |                                  5.55 |
| ('gt', 'artnet-exp', 8, 256, -1)      |                743.88 |                 760.15 |               781.61 |                               645.00 |                   6.09 |                    5.48 |                  6.42 |                                  7.91 |                         9.65 |                          8.46 |                        9.99 |                                       10.36 |                336.37 |                 361.42 |               441.22 |                               387.04 |                   2.95 |                    2.98 |                  3.58 |                                  2.45 |

## GATv2

In [16]:
print(build_speedup_table_with_dataset_index(no_reordering_df[(no_reordering_df[CONV_COL] == "gat_v2") & (no_reordering_df[BACKEND_COL] != "pyg")], "dgl").to_markdown(floatfmt=".2f"))

|                                    |   ('Bwd mem', 'cuda') |   ('Bwd mem', 'cugraph') |   ('Bwd time', 'cuda') |   ('Bwd time', 'cugraph') |   ('Fwd + Bwd time', 'cuda') |   ('Fwd + Bwd time', 'cugraph') |   ('Fwd mem', 'cuda') |   ('Fwd mem', 'cugraph') |   ('Fwd time', 'cuda') |   ('Fwd time', 'cugraph') |
|:-----------------------------------|----------------------:|-------------------------:|-----------------------:|--------------------------:|-----------------------------:|--------------------------------:|----------------------:|-------------------------:|-----------------------:|--------------------------:|
| ('gat_v2', 'artnet-exp', 2, 256)   |                  5.49 |                     4.83 |                   1.60 |                      1.43 |                         1.96 |                            1.53 |                  8.42 |                     4.51 |                   3.23 |                      1.72 |
| ('gat_v2', 'artnet-exp', 2, 512)   |                  5.47 |                     5.10 |                   1.43 |                      1.73 |                         1.59 |                            1.62 |                  8.58 |                     4.61 |                   1.97 |                      1.46 |
| ('gat_v2', 'artnet-exp', 4, 256)   |                  6.03 |                     9.28 |                   1.55 |                      2.95 |                         1.93 |                            3.21 |                  9.71 |                     8.80 |                   3.30 |                      3.71 |
| ('gat_v2', 'artnet-exp', 4, 512)   |                  6.02 |                     9.90 |                   1.50 |                      3.45 |                         1.64 |                            3.21 |                  9.88 |                     9.11 |                   1.97 |                      2.87 |
| ('gat_v2', 'artnet-exp', 8, 256)   |                  6.37 |                    18.19 |                   1.63 |                      6.15 |                         2.00 |                            6.57 |                 10.62 |                    17.48 |                   3.37 |                      7.39 |
| ('gat_v2', 'artnet-exp', 8, 512)   |                  6.35 |                    19.50 |                   1.43 |                      6.72 |                         1.60 |                            6.32 |                 10.70 |                    18.13 |                   1.97 |                      5.75 |
| ('gat_v2', 'artnet-views', 2, 256) |                  5.51 |                     4.85 |                   1.62 |                      1.53 |                         1.97 |                            1.60 |                  8.39 |                     4.48 |                   3.24 |                      1.73 |
| ('gat_v2', 'artnet-views', 2, 512) |                  5.48 |                     5.11 |                   1.43 |                      1.72 |                         1.59 |                            1.62 |                  8.64 |                     4.62 |                   1.97 |                      1.46 |
| ('gat_v2', 'artnet-views', 4, 256) |                  6.05 |                     9.32 |                   1.56 |                      3.00 |                         1.93 |                            3.23 |                  9.78 |                     8.85 |                   3.26 |                      3.67 |
| ('gat_v2', 'artnet-views', 4, 512) |                  6.03 |                     9.92 |                   1.50 |                      3.46 |                         1.64 |                            3.22 |                  9.91 |                     9.14 |                   1.96 |                      2.87 |
| ('gat_v2', 'artnet-views', 8, 256) |                  6.38 |                    18.27 |                   1.64 |                      6.18 |                         2.01 |                            6.56 |                 10.66 |                    17.57 |                   3.37 |                      7.31 |
| ('gat_v2', 'artnet-views', 8, 512) |                  6.36 |                    19.54 |                   1.44 |                      6.74 |                         1.60 |                            6.32 |                 10.72 |                    18.18 |                   1.96 |                      5.71 |
| ('gat_v2', 'citeseer', 2, 256)     |                  1.66 |                     2.00 |                   1.56 |                      1.22 |                         2.46 |                            1.61 |                  1.49 |                     1.56 |                   5.50 |                      2.20 |
| ('gat_v2', 'citeseer', 2, 512)     |                  1.85 |                     2.43 |                   1.19 |                      1.10 |                         1.49 |                            1.27 |                  1.73 |                     1.90 |                   2.16 |                      1.56 |
| ('gat_v2', 'citeseer', 4, 256)     |                  1.94 |                     3.25 |                   1.26 |                      1.48 |                         1.86 |                            1.88 |                  1.82 |                     2.34 |                   3.79 |                      2.54 |
| ('gat_v2', 'citeseer', 4, 512)     |                  1.98 |                     3.99 |                   1.16 |                      1.82 |                         1.21 |                            1.80 |                  2.09 |                     3.15 |                   1.33 |                      1.75 |
| ('gat_v2', 'citeseer', 8, 256)     |                  2.07 |                     5.41 |                   1.25 |                      2.35 |                         1.52 |                            2.49 |                  2.21 |                     3.90 |                   2.34 |                      2.72 |
| ('gat_v2', 'citeseer', 8, 512)     |                  1.94 |                     6.64 |                   1.13 |                      3.29 |                         1.21 |                            3.27 |                  2.44 |                     5.67 |                   1.38 |                      3.23 |
| ('gat_v2', 'city-reviews', 2, 256) |                  7.24 |                     5.43 |                   1.07 |                      0.40 |                         1.36 |                            0.47 |                 11.08 |                     4.72 |                   2.86 |                      0.68 |
| ('gat_v2', 'city-reviews', 2, 512) |                  7.36 |                     5.57 |                   1.27 |                      0.57 |                         1.44 |                            0.60 |                 11.68 |                     4.88 |                   1.87 |                      0.66 |
| ('gat_v2', 'city-reviews', 4, 256) |                  8.15 |                    10.61 |                   1.27 |                      0.76 |                         1.63 |                            0.92 |                 13.18 |                     9.34 |                   3.36 |                      1.37 |
| ('gat_v2', 'city-reviews', 4, 512) |                nan    |                   nan    |                 nan    |                    nan    |                       nan    |                          nan    |                 13.58 |                     9.67 |                   1.99 |                      1.27 |
| ('gat_v2', 'city-reviews', 8, 256) |                nan    |                   nan    |                 nan    |                    nan    |                       nan    |                          nan    |                 14.56 |                    18.55 |                   3.57 |                      2.59 |
| ('gat_v2', 'city-roads-L', 2, 256) |                  1.45 |                     2.51 |                   1.23 |                      2.64 |                         1.34 |                            2.69 |                  1.98 |                     2.55 |                   1.61 |                      2.79 |
| ('gat_v2', 'city-roads-L', 2, 512) |                  1.44 |                     2.55 |                   1.18 |                      3.19 |                         1.21 |                            3.11 |                  2.04 |                     2.67 |                   1.27 |                      2.95 |
| ('gat_v2', 'city-roads-L', 4, 256) |                  1.50 |                     4.50 |                   1.22 |                      5.59 |                         1.32 |                            5.79 |                  2.24 |                     4.80 |                   1.60 |                      6.22 |
| ('gat_v2', 'city-roads-L', 4, 512) |                  1.49 |                     4.62 |                   1.16 |                      6.04 |                         1.19 |                            5.97 |                  2.28 |                     5.10 |                   1.27 |                      5.83 |
| ('gat_v2', 'city-roads-L', 8, 256) |                  1.52 |                     8.44 |                   1.25 |                     11.42 |                         1.34 |                           11.69 |                  2.41 |                     9.31 |                   1.59 |                     12.28 |
| ('gat_v2', 'city-roads-L', 8, 512) |                  1.52 |                     8.76 |                   1.16 |                     11.76 |                         1.19 |                           11.71 |                  2.43 |                     9.97 |                   1.26 |                     11.62 |
| ('gat_v2', 'city-roads-M', 2, 256) |                  1.68 |                     2.61 |                   1.32 |                      2.58 |                         1.43 |                            2.66 |                  2.27 |                     2.78 |                   1.73 |                      2.85 |
| ('gat_v2', 'city-roads-M', 2, 512) |                  1.63 |                     2.79 |                   1.12 |                      2.98 |                         1.18 |                            2.97 |                  2.32 |                     2.88 |                   1.32 |                      2.94 |
| ('gat_v2', 'city-roads-M', 4, 256) |                  1.71 |                     4.67 |                   1.21 |                      5.22 |                         1.34 |                            5.34 |                  2.57 |                     5.34 |                   1.71 |                      5.59 |
| ('gat_v2', 'city-roads-M', 4, 512) |                  1.69 |                     5.11 |                   1.19 |                      6.05 |                         1.23 |                            5.96 |                  2.59 |                     5.57 |                   1.31 |                      5.78 |
| ('gat_v2', 'city-roads-M', 8, 256) |                  1.74 |                     8.81 |                   1.28 |                     11.05 |                         1.39 |                           11.34 |                  2.75 |                    10.44 |                   1.70 |                     11.97 |
| ('gat_v2', 'city-roads-M', 8, 512) |                  1.72 |                     9.71 |                   1.12 |                     11.60 |                         1.17 |                           11.57 |                  2.76 |                    10.94 |                   1.31 |                     11.50 |
| ('gat_v2', 'cora', 2, 256)         |                  2.27 |                     2.72 |                   1.38 |                      0.85 |                         2.22 |                            1.17 |                  2.02 |                     1.97 |                   5.31 |                      1.68 |
| ('gat_v2', 'cora', 2, 512)         |                  2.50 |                     3.30 |                   1.12 |                      0.71 |                         1.42 |                            0.82 |                  2.38 |                     2.48 |                   2.13 |                      1.02 |
| ('gat_v2', 'cora', 4, 256)         |                  2.70 |                     4.81 |                   1.14 |                      1.02 |                         1.71 |                            1.31 |                  2.57 |                     3.32 |                   3.80 |                      1.80 |
| ('gat_v2', 'cora', 4, 512)         |                  2.58 |                     5.53 |                   1.12 |                      1.11 |                         1.20 |                            1.12 |                  2.90 |                     4.45 |                   1.41 |                      1.14 |
| ('gat_v2', 'cora', 8, 256)         |                  2.76 |                     8.16 |                   1.18 |                      1.55 |                         1.47 |                            1.65 |                  3.12 |                     6.00 |                   2.46 |                      1.83 |
| ('gat_v2', 'cora', 8, 512)         |                  2.51 |                     9.50 |                   1.11 |                      1.93 |                         1.19 |                            1.93 |                  3.33 |                     8.41 |                   1.38 |                      1.94 |
| ('gat_v2', 'ogbn-arxiv', 2, 256)   |                  3.58 |                     4.22 |                   0.79 |                      2.17 |                         0.99 |                            2.31 |                  5.43 |                     3.99 |                   1.73 |                      2.57 |
| ('gat_v2', 'ogbn-arxiv', 2, 512)   |                  3.60 |                     4.30 |                   1.07 |                      2.28 |                         1.13 |                            2.14 |                  5.60 |                     4.13 |                   1.27 |                      1.94 |
| ('gat_v2', 'ogbn-arxiv', 4, 256)   |                  3.92 |                     8.07 |                   0.97 |                      3.97 |                         1.19 |                            4.24 |                  6.30 |                     7.84 |                   1.99 |                      4.74 |
| ('gat_v2', 'ogbn-arxiv', 4, 512)   |                  3.93 |                     8.27 |                   1.17 |                      4.23 |                         1.25 |                            3.98 |                  6.41 |                     8.12 |                   1.43 |                      3.61 |
| ('gat_v2', 'ogbn-arxiv', 8, 256)   |                  4.13 |                    15.77 |                   1.17 |                      7.80 |                         1.40 |                            8.18 |                  6.86 |                    15.51 |                   2.23 |                      8.87 |
| ('gat_v2', 'ogbn-arxiv', 8, 512)   |                nan    |                   nan    |                 nan    |                    nan    |                       nan    |                          nan    |                  6.92 |                    16.11 |                   1.55 |                      6.98 |
| ('gat_v2', 'pubmed', 2, 256)       |                  2.61 |                     3.25 |                   1.25 |                      1.09 |                         1.46 |                            1.18 |                  3.20 |                     2.97 |                   2.15 |                      1.39 |
| ('gat_v2', 'pubmed', 2, 512)       |                  2.56 |                     3.32 |                   1.20 |                      1.58 |                         1.29 |                            1.53 |                  3.51 |                     3.32 |                   1.49 |                      1.44 |
| ('gat_v2', 'pubmed', 4, 256)       |                  2.76 |                     5.75 |                   1.27 |                      2.16 |                         1.47 |                            2.29 |                  3.89 |                     5.62 |                   2.15 |                      2.55 |
| ('gat_v2', 'pubmed', 4, 512)       |                  2.73 |                     6.10 |                   1.22 |                      3.04 |                         1.30 |                            2.92 |                  4.12 |                     6.40 |                   1.48 |                      2.72 |
| ('gat_v2', 'pubmed', 8, 256)       |                  2.86 |                    10.76 |                   1.36 |                      4.35 |                         1.56 |                            4.70 |                  4.40 |                    10.89 |                   2.18 |                      5.48 |
| ('gat_v2', 'pubmed', 8, 512)       |                  2.86 |                    11.78 |                   1.25 |                      5.96 |                         1.33 |                            5.78 |                  4.53 |                    12.55 |                   1.49 |                      5.47 |
| ('gat_v2', 'tolokers-2', 2, 256)   |                 36.43 |                     7.24 |                   1.65 |                      0.54 |                         2.22 |                            0.64 |                 52.21 |                     5.51 |                   5.77 |                      0.85 |
| ('gat_v2', 'tolokers-2', 2, 512)   |                 37.26 |                     7.30 |                   1.88 |                      0.60 |                         2.26 |                            0.64 |                 57.45 |                     5.66 |                   3.21 |                      0.71 |
| ('gat_v2', 'tolokers-2', 4, 256)   |                 42.01 |                    14.15 |                   1.94 |                      1.03 |                         2.66 |                            1.25 |                 65.27 |                    10.98 |                   7.19 |                      1.82 |
| ('gat_v2', 'tolokers-2', 4, 512)   |                 42.31 |                    14.42 |                   2.08 |                      1.13 |                         2.51 |                            1.23 |                 68.61 |                    11.27 |                   3.56 |                      1.40 |
| ('gat_v2', 'tolokers-2', 8, 256)   |                 45.63 |                    28.00 |                   2.16 |                      2.01 |                         3.04 |                            2.46 |                 74.59 |                    21.89 |                   8.51 |                      3.60 |
| ('gat_v2', 'tolokers-2', 8, 512)   |                 45.41 |                    28.65 |                   2.27 |                      2.22 |                         2.68 |                            2.39 |                 76.02 |                    22.51 |                   3.68 |                      2.70 |

In [17]:
print(build_raw_table_with_dataset_index(no_reordering_df[(no_reordering_df[CONV_COL] == "gat_v2") & (no_reordering_df[BACKEND_COL] != "pyg")]).to_markdown(floatfmt=".2f"))

|                                     |   ('Bwd mem', 'cuda') |   ('Bwd mem', 'cugraph') |   ('Bwd mem', 'dgl') |   ('Bwd time', 'cuda') |   ('Bwd time', 'cugraph') |   ('Bwd time', 'dgl') |   ('Fwd + Bwd time', 'cuda') |   ('Fwd + Bwd time', 'cugraph') |   ('Fwd + Bwd time', 'dgl') |   ('Fwd mem', 'cuda') |   ('Fwd mem', 'cugraph') |   ('Fwd mem', 'dgl') |   ('Fwd time', 'cuda') |   ('Fwd time', 'cugraph') |   ('Fwd time', 'dgl') |
|:------------------------------------|----------------------:|-------------------------:|---------------------:|-----------------------:|--------------------------:|----------------------:|-----------------------------:|--------------------------------:|----------------------------:|----------------------:|-------------------------:|---------------------:|-----------------------:|--------------------------:|----------------------:|
| ('gat_v2', 'artnet-exp', 2, 256)    |                925.47 |                  1052.09 |              5083.21 |                   8.95 |                     10.01 |                 14.36 |                        11.84 |                           15.17 |                       23.25 |                426.46 |                   796.49 |              3589.36 |                   2.75 |                      5.16 |                  8.89 |
| ('gat_v2', 'artnet-exp', 2, 512)    |               1821.34 |                  1953.26 |              9960.55 |                  25.98 |                     21.50 |                 37.16 |                        37.24 |                           36.54 |                       59.17 |                830.66 |                  1547.91 |              7130.81 |                  11.19 |                     15.05 |                 22.01 |
| ('gat_v2', 'artnet-exp', 4, 256)    |               1619.61 |                  1052.09 |              9766.98 |                  17.87 |                      9.39 |                 27.70 |                        23.68 |                           14.22 |                       45.65 |                729.59 |                   804.62 |              7083.64 |                   5.43 |                      4.83 |                 17.93 |
| ('gat_v2', 'artnet-exp', 4, 512)    |               3213.04 |                  1953.26 |             19334.00 |                  49.66 |                     21.49 |                 74.24 |                        71.79 |                           36.64 |                      117.66 |               1427.52 |                  1547.91 |             14106.52 |                  22.07 |                     15.15 |                 43.42 |
| ('gat_v2', 'artnet-exp', 8, 256)    |               3004.76 |                  1052.09 |             19142.16 |                  35.04 |                      9.29 |                 57.13 |                        46.19 |                           14.08 |                       92.50 |               1324.30 |                   804.62 |             14060.13 |                  10.50 |                      4.79 |                 35.27 |
| ('gat_v2', 'artnet-exp', 8, 512)    |               5995.50 |                  1953.26 |             38078.91 |                 100.72 |                     21.49 |                144.51 |                       144.61 |                           36.52 |                      230.95 |               2622.51 |                  1547.91 |             28056.61 |                  43.87 |                     15.03 |                 86.31 |
| ('gat_v2', 'artnet-views', 2, 256)  |                920.66 |                  1047.29 |              5075.73 |                   8.90 |                      9.38 |                 14.39 |                        11.85 |                           14.52 |                       23.31 |                426.93 |                   799.81 |              3581.89 |                   2.75 |                      5.14 |                  8.90 |
| ('gat_v2', 'artnet-views', 2, 512)  |               1815.90 |                  1948.45 |              9956.30 |                  25.94 |                     21.51 |                 37.09 |                        37.11 |                           36.56 |                       59.10 |                825.22 |                  1543.10 |              7126.56 |                  11.15 |                     15.05 |                 21.96 |
| ('gat_v2', 'artnet-views', 4, 256)  |               1613.18 |                  1047.29 |              9761.41 |                  17.84 |                      9.25 |                 27.77 |                        23.52 |                           14.05 |                       45.37 |                724.15 |                   799.81 |              7078.06 |                   5.40 |                      4.80 |                 17.61 |
| ('gat_v2', 'artnet-views', 4, 512)  |               3206.97 |                  1948.45 |             19328.64 |                  49.57 |                     21.49 |                 74.43 |                        71.65 |                           36.55 |                      117.65 |               1422.29 |                  1543.10 |             14101.15 |                  22.00 |                     15.05 |                 43.22 |
| ('gat_v2', 'artnet-views', 8, 256)  |               2998.92 |                  1047.29 |             19136.30 |                  34.94 |                      9.27 |                 57.25 |                        46.11 |                           14.09 |                       92.45 |               1318.68 |                   799.81 |             14054.49 |                  10.46 |                      4.82 |                 35.21 |
| ('gat_v2', 'artnet-views', 8, 512)  |               5989.82 |                  1948.45 |             38074.66 |                 100.43 |                     21.48 |                144.87 |                       144.42 |                           36.53 |                      230.75 |               2616.93 |                  1543.10 |             28050.96 |                  43.76 |                     15.04 |                 85.88 |
| ('gat_v2', 'avazu-ctr', 2, 256)     |               1605.72 |                 23235.54 |               nan    |                 241.83 |                   2967.36 |                nan    |                       293.82 |                         3314.48 |                      nan    |                859.40 |                 22770.51 |               nan    |                  41.79 |                    347.12 |                nan    |
| ('gat_v2', 'avazu-ctr', 2, 512)     |               2955.60 |                 45287.34 |               nan    |                 341.03 |                   3403.95 |                nan    |                       487.02 |                         4103.09 |                      nan    |               1459.75 |                 44522.49 |               nan    |                 144.63 |                    699.15 |                nan    |
| ('gat_v2', 'avazu-ctr', 4, 256)     |               2652.55 |                 23235.54 |               nan    |                 357.73 |                   2963.85 |                nan    |                       432.67 |                         3311.63 |                      nan    |               1308.37 |                 22770.11 |               nan    |                  58.52 |                    347.79 |                nan    |
| ('gat_v2', 'avazu-ctr', 4, 512)     |               5054.19 |                 45287.34 |               nan    |                 558.74 |                   3395.76 |                nan    |                       802.72 |                         4095.65 |                      nan    |               2360.27 |                 44522.49 |               nan    |                 241.63 |                    699.89 |                nan    |
| ('gat_v2', 'avazu-ctr', 8, 256)     |               4745.44 |                 23235.54 |               nan    |                 589.56 |                   2967.45 |                nan    |                       710.48 |                         3316.32 |                      nan    |               2206.47 |                 22770.11 |               nan    |                  91.15 |                    348.86 |                nan    |
| ('gat_v2', 'avazu-ctr', 8, 512)     |               9251.36 |                 45287.34 |               nan    |                1002.45 |                   3404.68 |                nan    |                      1440.10 |                         4105.49 |                      nan    |               4161.44 |                 44522.49 |               nan    |                 433.09 |                    700.81 |                nan    |
| ('gat_v2', 'citeseer', 2, 256)      |                124.97 |                   103.65 |               206.33 |                   0.89 |                      1.14 |                  1.39 |                         1.24 |                            1.89 |                        3.05 |                 90.98 |                    87.15 |               134.82 |                   0.30 |                      0.75 |                  1.63 |
| ('gat_v2', 'citeseer', 2, 512)      |                192.39 |                   146.48 |               354.69 |                   1.92 |                      2.08 |                  2.30 |                         2.75 |                            3.23 |                        4.08 |                121.40 |                   110.47 |               209.00 |                   0.83 |                      1.15 |                  1.79 |
| ('gat_v2', 'citeseer', 4, 256)      |                173.43 |                   103.65 |               335.85 |                   1.31 |                      1.12 |                  1.66 |                         1.81 |                            1.79 |                        3.37 |                111.94 |                    87.15 |               202.89 |                   0.45 |                      0.67 |                  1.71 |
| ('gat_v2', 'citeseer', 4, 512)      |                295.40 |                   146.48 |               585.08 |                   3.25 |                      2.07 |                  3.77 |                         4.78 |                            3.22 |                        5.79 |                166.42 |                   110.47 |               347.76 |                   1.52 |                      1.15 |                  2.02 |
| ('gat_v2', 'citeseer', 8, 256)      |                270.52 |                   103.65 |               560.56 |                   2.12 |                      1.13 |                  2.65 |                         2.93 |                            1.79 |                        4.46 |                153.99 |                    87.15 |               338.72 |                   0.77 |                      0.67 |                  1.79 |
| ('gat_v2', 'citeseer', 8, 512)      |                501.41 |                   146.48 |               971.30 |                   5.99 |                      2.06 |                  6.77 |                         8.67 |                            3.21 |                       10.47 |                256.46 |                   110.47 |               625.26 |                   2.68 |                      1.15 |                  3.71 |
| ('gat_v2', 'city-reviews', 2, 256)  |               2773.62 |                  3697.05 |             20087.32 |                  52.55 |                    141.97 |                 56.32 |                        67.83 |                          195.04 |                       92.30 |               1318.24 |                  3095.54 |             14609.40 |                  12.62 |                     53.07 |                 35.98 |
| ('gat_v2', 'city-reviews', 2, 512)  |               5400.70 |                  7132.83 |             39759.37 |                 107.76 |                    240.08 |                136.14 |                       152.39 |                          365.01 |                      219.00 |               2485.58 |                  5951.54 |             29034.87 |                  44.41 |                    124.93 |                 82.84 |
| ('gat_v2', 'city-reviews', 4, 256)  |               4813.51 |                  3696.61 |             39207.38 |                  85.13 |                    142.36 |                108.03 |                       109.82 |                          193.85 |                      178.34 |               2193.37 |                  3095.33 |             28904.31 |                  20.95 |                     51.49 |                 70.30 |
| ('gat_v2', 'city-reviews', 4, 512)  |               9481.75 |                  7132.83 |               nan    |                 186.28 |                    241.13 |                nan    |                       266.33 |                          365.78 |                      nan    |               4237.48 |                  5951.54 |             57536.72 |                  79.78 |                    124.66 |                158.51 |
| ('gat_v2', 'city-reviews', 8, 256)  |               8891.04 |                  3696.61 |               nan    |                 147.39 |                    142.33 |                nan    |                       190.95 |                          194.60 |                      nan    |               3943.35 |                  3095.33 |             57421.16 |                  37.81 |                     52.27 |                135.14 |
| ('gat_v2', 'city-reviews', 8, 512)  |              17647.22 |                  7132.83 |               nan    |                 343.07 |                    240.90 |                nan    |                       493.08 |                          366.00 |                      nan    |               7738.94 |                  5951.54 |               nan    |                 149.85 |                    125.10 |                nan    |
| ('gat_v2', 'city-roads-L', 2, 256)  |               2640.12 |                  1530.60 |              3834.03 |                  16.96 |                      7.93 |                 20.92 |                        23.58 |                           11.75 |                       31.60 |               1248.77 |                   973.27 |              2476.18 |                   6.62 |                      3.82 |                 10.68 |
| ('gat_v2', 'city-roads-L', 2, 512)  |               5151.30 |                  2919.70 |              7437.70 |                  58.50 |                     21.60 |                 68.74 |                        84.28 |                           32.70 |                      101.52 |               2365.46 |                  1804.56 |              4813.45 |                  25.76 |                     11.10 |                 32.78 |
| ('gat_v2', 'city-roads-L', 4, 256)  |               4590.23 |                  1530.60 |              6879.97 |                  33.76 |                      7.34 |                 41.04 |                        47.11 |                           10.72 |                       62.09 |               2085.39 |                   973.27 |              4673.70 |                  13.19 |                      3.39 |                 21.06 |
| ('gat_v2', 'city-roads-L', 4, 512)  |               9054.55 |                  2919.70 |             13483.60 |                 112.16 |                     21.59 |                130.29 |                       163.41 |                           32.70 |                      194.96 |               4039.13 |                  1804.56 |              9204.13 |                  51.07 |                     11.10 |                 64.67 |
| ('gat_v2', 'city-roads-L', 8, 256)  |               8488.57 |                  1530.60 |             12923.70 |                  66.75 |                      7.32 |                 83.55 |                        93.18 |                           10.70 |                      125.11 |               3757.33 |                   973.27 |              9063.55 |                  26.21 |                      3.39 |                 41.56 |
| ('gat_v2', 'city-roads-L', 8, 512)  |              16858.45 |                  2919.70 |             25569.31 |                 220.32 |                     21.65 |                254.37 |                       322.83 |                           32.76 |                      383.35 |               7387.23 |                  1804.56 |             17982.12 |                 102.27 |                     11.11 |                128.98 |
| ('gat_v2', 'city-roads-M', 2, 256)  |               1040.00 |                   668.64 |              1744.68 |                   6.82 |                      3.48 |                  8.96 |                         9.60 |                            5.14 |                       13.66 |                481.14 |                   393.16 |              1094.10 |                   2.73 |                      1.66 |                  4.70 |
| ('gat_v2', 'city-roads-M', 2, 512)  |               2052.24 |                  1197.66 |              3347.37 |                  24.27 |                      9.13 |                 27.21 |                        34.80 |                           13.86 |                       41.13 |                931.52 |                   747.58 |              2156.52 |                  10.53 |                      4.73 |                 13.90 |
| ('gat_v2', 'city-roads-M', 4, 256)  |               1823.73 |                   668.64 |              3120.14 |                  14.04 |                      3.24 |                 16.91 |                        19.54 |                            4.91 |                       26.16 |                817.49 |                   393.16 |              2098.80 |                   5.44 |                      1.66 |                  9.26 |
| ('gat_v2', 'city-roads-M', 4, 512)  |               3625.61 |                  1197.66 |              6124.04 |                  46.40 |                      9.12 |                 55.18 |                        67.29 |                           13.86 |                       82.54 |               1606.79 |                   747.58 |              4163.40 |                  20.86 |                      4.73 |                 27.26 |
| ('gat_v2', 'city-roads-M', 8, 256)  |               3391.54 |                   668.64 |              5893.14 |                  27.73 |                      3.21 |                 35.50 |                        38.55 |                            4.72 |                       53.60 |               1490.19 |                   393.16 |              4103.65 |                  10.62 |                      1.51 |                 18.01 |
| ('gat_v2', 'city-roads-M', 8, 512)  |               6772.51 |                  1197.66 |             11633.32 |                  94.90 |                      9.13 |                105.86 |                       136.52 |                           13.86 |                      160.03 |               2957.55 |                   747.58 |              8177.07 |                  41.59 |                      4.72 |                 54.16 |
| ('gat_v2', 'cora', 2, 256)          |                 81.82 |                    68.29 |               185.90 |                   1.02 |                      1.65 |                  1.38 |                         1.39 |                            2.66 |                        3.01 |                 53.88 |                    55.23 |               108.76 |                   0.32 |                      1.01 |                  1.64 |

## GCN

In [18]:
print(build_speedup_table_with_dataset_index(no_reordering_df[no_reordering_df[CONV_COL] == "gcn"], "dgl").to_markdown(floatfmt=".2f"))

|                                  |   ('Bwd mem', 'cusparse') |   ('Bwd mem', 'cusparse_precomputed_bwd') |   ('Bwd mem', 'fusegnn') |   ('Bwd mem', 'pyg') |   ('Bwd mem', 'tcgnn') |   ('Bwd mem', 'torch_native_gcn') |   ('Bwd mem', 'triton_block_sparse') |   ('Bwd time', 'cusparse') |   ('Bwd time', 'cusparse_precomputed_bwd') |   ('Bwd time', 'fusegnn') |   ('Bwd time', 'pyg') |   ('Bwd time', 'tcgnn') |   ('Bwd time', 'torch_native_gcn') |   ('Bwd time', 'triton_block_sparse') |   ('Fwd + Bwd time', 'cusparse') |   ('Fwd + Bwd time', 'cusparse_precomputed_bwd') |   ('Fwd + Bwd time', 'fusegnn') |   ('Fwd + Bwd time', 'pyg') |   ('Fwd + Bwd time', 'tcgnn') |   ('Fwd + Bwd time', 'torch_native_gcn') |   ('Fwd + Bwd time', 'triton_block_sparse') |   ('Fwd mem', 'cusparse') |   ('Fwd mem', 'cusparse_precomputed_bwd') |   ('Fwd mem', 'fusegnn') |   ('Fwd mem', 'pyg') |   ('Fwd mem', 'tcgnn') |   ('Fwd mem', 'torch_native_gcn') |   ('Fwd mem', 'triton_block_sparse') |   ('Fwd time', 'cusparse') |   ('Fwd time', 'cusparse_precomputed_bwd') |   ('Fwd time', 'fusegnn') |   ('Fwd time', 'pyg') |   ('Fwd time', 'tcgnn') |   ('Fwd time', 'torch_native_gcn') |   ('Fwd time', 'triton_block_sparse') |
|:---------------------------------|--------------------------:|------------------------------------------:|-------------------------:|---------------------:|-----------------------:|----------------------------------:|-------------------------------------:|---------------------------:|-------------------------------------------:|--------------------------:|----------------------:|------------------------:|-----------------------------------:|--------------------------------------:|---------------------------------:|-------------------------------------------------:|--------------------------------:|----------------------------:|------------------------------:|-----------------------------------------:|--------------------------------------------:|--------------------------:|------------------------------------------:|-------------------------:|---------------------:|-----------------------:|----------------------------------:|-------------------------------------:|---------------------------:|-------------------------------------------:|--------------------------:|----------------------:|------------------------:|-----------------------------------:|--------------------------------------:|
| ('gcn', 'artnet-exp', 1, 64)     |                      1.41 |                                      1.37 |                     0.05 |                 0.04 |                   1.39 |                              1.06 |                                 0.97 |                       1.77 |                                       1.51 |                      1.44 |                  0.38 |                    0.62 |                               0.47 |                                  1.55 |                             4.08 |                                             3.69 |                            0.38 |                        0.61 |                          1.40 |                                     1.54 |                                        3.22 |                      2.05 |                                      1.95 |                     0.04 |                 0.03 |                   1.97 |                              1.43 |                                 1.17 |                       7.26 |                                       7.15 |                      0.31 |                  0.76 |                    2.45 |                               6.46 |                                  5.05 |
| ('gcn', 'artnet-exp', 1, 128)    |                      1.32 |                                      1.30 |                     0.08 |                 0.06 |                   1.31 |                              1.03 |                                 0.98 |                       1.35 |                                       1.63 |                      1.17 |                  0.23 |                    0.62 |                               0.51 |                                  1.49 |                             3.03 |                                             3.41 |                            0.36 |                        0.36 |                          1.15 |                                     1.45 |                                        2.91 |                      1.96 |                                      1.90 |                     0.06 |                 0.05 |                   1.98 |                              1.39 |                                 1.29 |                       6.05 |                                       6.05 |                      0.28 |                  0.46 |                    1.75 |                               5.74 |                                  4.72 |
| ('gcn', 'artnet-exp', 1, 256)    |                      1.26 |                                      1.25 |                     0.13 |                 0.09 |                   1.26 |                              1.02 |                                 0.99 |                       1.17 |                                       1.48 |                      1.46 |                  0.17 |                    0.82 |                               0.62 |                                  1.40 |                             2.10 |                                             2.44 |                            0.40 |                        0.22 |                          1.21 |                                     1.29 |                                        2.40 |                      1.98 |                                      1.94 |                     0.10 |                 0.07 |                   1.99 |                              1.37 |                                 1.41 |                       3.88 |                                       3.88 |                      0.28 |                  0.27 |                    1.67 |                               3.57 |                                  4.09 |
| ('gcn', 'artnet-exp', 1, 512)    |                      1.23 |                                      1.23 |                     0.22 |                 0.12 |                   1.23 |                              1.01 |                                 0.99 |                       1.08 |                                       1.48 |                      1.36 |                  0.15 |                    1.12 |                               0.77 |                                  1.34 |                             1.65 |                                             2.01 |                            0.44 |                        0.17 |                          1.41 |                                     1.26 |                                        2.01 |                      1.99 |                                      1.97 |                     0.17 |                 0.09 |                   1.99 |                              1.35 |                                 1.48 |                       2.76 |                                       2.78 |                      0.29 |                  0.18 |                    1.77 |                               2.44 |                                  3.28 |
| ('gcn', 'artnet-views', 1, 64)   |                      0.05 |                                      0.02 |                     0.05 |                 0.04 |                   1.41 |                              1.06 |                                 0.98 |                       1.72 |                                       1.72 |                      1.60 |                  0.41 |                    0.65 |                               0.46 |                                  1.58 |                             3.75 |                                             3.87 |                            0.45 |                        0.63 |                          1.40 |                                     1.43 |                                        3.13 |                      0.04 |                                      0.02 |                     0.04 |                 0.03 |                   2.11 |                              1.48 |                                 1.19 |                       6.47 |                                       6.91 |                      0.36 |                  0.77 |                    2.40 |                               5.96 |                                  4.81 |
| ('gcn', 'artnet-views', 1, 128)  |                      0.08 |                                      0.03 |                     0.08 |                 0.06 |                   1.32 |                              1.04 |                                 0.99 |                       1.26 |                                       1.25 |                      1.13 |                  0.23 |                    0.59 |                               0.45 |                                  1.47 |                             2.77 |                                             2.86 |                            0.50 |                        0.37 |                          1.12 |                                     1.32 |                                        2.90 |                      0.06 |                                      0.02 |                     0.06 |                 0.05 |                   2.07 |                              1.42 |                                 1.31 |                       5.19 |                                       5.71 |                      0.41 |                  0.47 |                    1.70 |                               5.11 |                                  4.65 |
| ('gcn', 'artnet-views', 1, 256)  |                      0.14 |                                      0.06 |                     0.13 |                 0.09 |                   1.26 |                              1.02 |                                 0.99 |                       1.13 |                                       1.37 |                      1.43 |                  0.17 |                    0.79 |                               0.53 |                                  1.36 |                             2.07 |                                             2.36 |                            0.56 |                        0.23 |                          1.20 |                                     1.17 |                                        2.41 |                      0.10 |                                      0.04 |                     0.10 |                 0.07 |                   2.04 |                              1.38 |                                 1.42 |                       3.86 |                                       3.94 |                      0.42 |                  0.28 |                    1.67 |                               3.46 |                                  4.22 |
| ('gcn', 'artnet-views', 1, 512)  |                      0.23 |                                      0.10 |                     0.22 |                 0.12 |                   1.23 |                              1.01 |                                 1.00 |                       4.43 |                                       5.92 |                      5.76 |                  0.61 |                    4.64 |                               3.05 |                                  5.58 |                             3.88 |                                             4.67 |                            0.83 |                        0.39 |                          3.33 |                                     2.85 |                                        4.76 |                      0.18 |                                      0.07 |                     0.17 |                 0.09 |                   2.02 |                              1.36 |                                 1.49 |                       2.77 |                                       2.79 |                      0.22 |                  0.19 |                    1.75 |                               2.35 |                                  3.25 |
| ('gcn', 'avazu-ctr', 1, 64)      |                      0.56 |                                      0.23 |                     0.40 |                 0.09 |                   2.54 |                              0.67 |                                 1.25 |                       0.74 |                                       1.16 |                      0.25 |                  0.09 |                    0.01 |                               0.17 |                                  1.01 |                             1.01 |                                             1.30 |                            0.21 |                        0.09 |                          0.01 |                                     0.32 |                                        1.25 |                      0.57 |                                      0.23 |                     0.31 |                 0.09 |                   3.37 |                              2.20 |                                 1.29 |                       1.45 |                                       1.46 |                      0.18 |                  0.10 |                    0.01 |                               1.23 |                                  1.57 |
| ('gcn', 'avazu-ctr', 1, 128)     |                      0.59 |                                      0.25 |                     0.42 |                 0.06 |                   2.32 |                              0.70 |                                 1.22 |                       0.50 |                                       1.09 |                      0.16 |                  0.04 |                    0.01 |                               0.18 |                                  1.02 |                             0.77 |                                             1.21 |                            0.15 |                        0.05 |                          0.01 |                                     0.33 |                                        1.27 |                      0.57 |                                      0.23 |                     0.33 |                 0.05 |                   3.18 |                              2.09 |                                 1.28 |                       1.40 |                                       1.33 |                      0.14 |                  0.05 |                    0.01 |                               1.25 |                                  1.61 |
| ('gcn', 'avazu-ctr', 1, 256)     |                      0.63 |                                      0.28 |                     0.46 |                 0.03 |                   2.07 |                              0.76 |                                 1.19 |                       0.53 |                                       1.20 |                      0.38 |                  0.04 |                    0.02 |                               0.32 |                                  1.08 |                             0.75 |                                             1.23 |                            0.32 |                        0.04 |                          0.02 |                                     0.51 |                                        1.49 |                      0.60 |                                      0.25 |                     0.35 |                 0.03 |                   2.93 |                              1.93 |                                 1.28 |                       1.25 |                                       1.27 |                      0.28 |                  0.04 |                    0.02 |                               1.14 |                                  2.34 |
| ('gcn', 'avazu-ctr', 1, 512)     |                      0.70 |                                      0.33 |                     0.53 |               nan    |                   1.79 |                              0.85 |                                 1.14 |                       0.53 |                                       1.16 |                      0.36 |                nan    |                    0.03 |                               0.48 |                                  1.05 |                             0.74 |                                             1.19 |                            0.33 |                      nan    |                          0.03 |                                     0.67 |                                        1.59 |                      0.67 |                                      0.29 |                     0.41 |               nan    |                   2.68 |                              1.77 |                                 1.31 |                       1.22 |                                       1.22 |                      0.30 |                nan    |                    0.03 |                               1.09 |                                  3.22 |
| ('gcn', 'citeseer', 1, 64)       |                      0.02 |                                      0.01 |                     0.02 |                 0.02 |                   1.02 |                              1.00 |                                 1.00 |                       1.93 |                                       1.83 |                      2.03 |                  1.98 |                    0.84 |                               0.43 |                                  1.79 |                             4.90 |                                             4.94 |                            0.67 |                        1.56 |                          2.83 |                                     1.58 |                                        3.61 |                      0.02 |                                      0.01 |                     0.02 |                 0.02 |                   1.04 |                              1.02 |                                 1.02 |                       9.95 |                                      11.30 |                      0.55 |                  1.46 |                   12.76 |                              12.21 |                                  5.42 |
| ('gcn', 'citeseer', 1, 128)      |                      0.02 |                                      0.01 |                     0.02 |                 0.02 |                   1.04 |                              1.00 |                                 1.00 |                       2.35 |                                       1.22 |                      2.64 |                  2.11 |                    1.03 |                               0.53 |                                  1.75 |                             6.44 |                                             3.85 |                            0.70 |                        1.60 |                          3.46 |                                     1.92 |                                        3.65 |                      0.02 |                                      0.01 |                     0.02 |                 0.02 |                   1.07 |                              1.04 |                                 1.05 |                      14.93 |                                      12.80 |                      0.56 |                  1.48 |                   14.77 |                              12.72 |                                  5.67 |

In [19]:
print(build_raw_table_with_dataset_index(no_reordering_df[no_reordering_df[CONV_COL] == "gcn"]).to_markdown(floatfmt=".2f"))

|                                  |   ('Bwd mem', 'cusparse') |   ('Bwd mem', 'cusparse_precomputed_bwd') |   ('Bwd mem', 'dgl') |   ('Bwd mem', 'fusegnn') |   ('Bwd mem', 'pyg') |   ('Bwd mem', 'tcgnn') |   ('Bwd mem', 'torch_native_gcn') |   ('Bwd mem', 'triton_block_sparse') |   ('Bwd time', 'cusparse') |   ('Bwd time', 'cusparse_precomputed_bwd') |   ('Bwd time', 'dgl') |   ('Bwd time', 'fusegnn') |   ('Bwd time', 'pyg') |   ('Bwd time', 'tcgnn') |   ('Bwd time', 'torch_native_gcn') |   ('Bwd time', 'triton_block_sparse') |   ('Fwd + Bwd time', 'cusparse') |   ('Fwd + Bwd time', 'cusparse_precomputed_bwd') |   ('Fwd + Bwd time', 'dgl') |   ('Fwd + Bwd time', 'fusegnn') |   ('Fwd + Bwd time', 'pyg') |   ('Fwd + Bwd time', 'tcgnn') |   ('Fwd + Bwd time', 'torch_native_gcn') |   ('Fwd + Bwd time', 'triton_block_sparse') |   ('Fwd mem', 'cusparse') |   ('Fwd mem', 'cusparse_precomputed_bwd') |   ('Fwd mem', 'dgl') |   ('Fwd mem', 'fusegnn') |   ('Fwd mem', 'pyg') |   ('Fwd mem', 'tcgnn') |   ('Fwd mem', 'torch_native_gcn') |   ('Fwd mem', 'triton_block_sparse') |   ('Fwd time', 'cusparse') |   ('Fwd time', 'cusparse_precomputed_bwd') |   ('Fwd time', 'dgl') |   ('Fwd time', 'fusegnn') |   ('Fwd time', 'pyg') |   ('Fwd time', 'tcgnn') |   ('Fwd time', 'torch_native_gcn') |   ('Fwd time', 'triton_block_sparse') |
|:---------------------------------|--------------------------:|------------------------------------------:|---------------------:|-------------------------:|---------------------:|-----------------------:|----------------------------------:|-------------------------------------:|---------------------------:|-------------------------------------------:|----------------------:|--------------------------:|----------------------:|------------------------:|-----------------------------------:|--------------------------------------:|---------------------------------:|-------------------------------------------------:|----------------------------:|--------------------------------:|----------------------------:|------------------------------:|-----------------------------------------:|--------------------------------------------:|--------------------------:|------------------------------------------:|---------------------:|-------------------------:|---------------------:|-----------------------:|----------------------------------:|-------------------------------------:|---------------------------:|-------------------------------------------:|----------------------:|--------------------------:|----------------------:|------------------------:|-----------------------------------:|--------------------------------------:|
| ('gcn', 'artnet-exp', 1, 64)     |                     83.86 |                                     86.19 |               118.34 |                  2427.34 |              2713.42 |                  85.44 |                            111.88 |                               121.42 |                       0.23 |                                       0.27 |                  0.39 |                      0.29 |                  1.09 |                    0.67 |                               0.88 |                                  0.27 |                             0.40 |                                             0.45 |                        1.60 |                            4.29 |                        2.71 |                          1.17 |                                     1.07 |                                        0.51 |                     44.42 |                                     46.75 |                91.19 |                  2398.58 |              2688.81 |                  46.19 |                             63.88 |                                78.17 |                       0.17 |                                       0.17 |                  1.21 |                      4.00 |                  1.62 |                    0.50 |                               0.19 |                                  0.24 |
| ('gcn', 'artnet-exp', 1, 128)    |                    145.39 |                                    147.72 |               192.18 |                  2489.02 |              3061.03 |                 146.96 |                            186.46 |                               195.25 |                       0.35 |                                       0.29 |                  0.45 |                      0.40 |                  2.04 |                    0.76 |                               0.93 |                                  0.32 |                             0.54 |                                             0.48 |                        1.59 |                            4.61 |                        4.57 |                          1.43 |                                     1.13 |                                        0.56 |                     71.55 |                                     73.89 |               140.41 |                  2419.92 |              3011.81 |                  70.80 |                            100.79 |                               108.93 |                       0.19 |                                       0.19 |                  1.14 |                      4.20 |                  2.53 |                    0.67 |                               0.20 |                                  0.25 |
| ('gcn', 'artnet-exp', 1, 256)    |                    272.33 |                                    274.66 |               344.09 |                  2612.08 |              3756.26 |                 273.90 |                            338.79 |                               347.58 |                       0.58 |                                       0.46 |                  0.67 |                      0.46 |                  4.08 |                    0.83 |                               1.10 |                                  0.48 |                             0.88 |                                             0.76 |                        1.85 |                            4.67 |                        8.43 |                          1.53 |                                     1.43 |                                        0.77 |                    122.33 |                                    124.66 |               241.96 |                  2469.14 |              3657.81 |                 121.57 |                            176.96 |                               172.01 |                       0.30 |                                       0.30 |                  1.17 |                      4.20 |                  4.34 |                    0.70 |                               0.33 |                                  0.29 |
| ('gcn', 'artnet-exp', 1, 512)    |                    514.57 |                                    516.90 |               634.77 |                  2858.20 |              5147.59 |                 516.14 |                            629.47 |                               638.26 |                       1.04 |                                       0.76 |                  1.11 |                      0.83 |                  7.50 |                    1.00 |                               1.46 |                                  0.84 |                             1.57 |                                             1.29 |                        2.57 |                            5.87 |                       15.46 |                          1.83 |                                     2.06 |                                        1.29 |                    219.23 |                                    221.56 |               435.75 |                  2567.59 |              4950.70 |                 218.47 |                            322.30 |                               294.30 |                       0.53 |                                       0.53 |                  1.46 |                      5.05 |                  7.96 |                    0.83 |                               0.60 |                                  0.45 |
| ('gcn', 'artnet-views', 1, 64)   |                   2277.55 |                                   5755.10 |               113.89 |                  2423.89 |              2708.61 |                  80.63 |                            107.82 |                               116.42 |                       0.25 |                                       0.25 |                  0.39 |                      0.26 |                  1.03 |                    0.66 |                               0.93 |                                  0.27 |                             0.43 |                                             0.42 |                        1.59 |                            3.64 |                        2.58 |                          1.16 |                                     1.13 |                                        0.52 |                   2238.11 |                                   5715.53 |                87.15 |                  2393.53 |              2684.00 |                  41.38 |                             59.07 |                                73.17 |                       0.19 |                                       0.17 |                  1.20 |                      3.37 |                  1.55 |                    0.50 |                               0.20 |                                  0.25 |
| ('gcn', 'artnet-views', 1, 128)  |                   2339.08 |                                   5816.63 |               187.72 |                  2485.41 |              3056.22 |                 142.16 |                            180.90 |                               190.25 |                       0.35 |                                       0.36 |                  0.45 |                      0.39 |                  1.93 |                    0.75 |                               0.98 |                                  0.30 |                             0.58 |                                             0.56 |                        1.59 |                            3.20 |                        4.36 |                          1.43 |                                     1.21 |                                        0.55 |                   2265.25 |                                   5742.79 |               136.37 |                  2415.24 |              3007.00 |                  65.99 |                             95.99 |                               103.93 |                       0.22 |                                       0.20 |                  1.15 |                      2.80 |                  2.43 |                    0.68 |                               0.23 |                                  0.25 |
| ('gcn', 'artnet-views', 1, 256)  |                   2462.14 |                                   5941.24 |               340.05 |                  2607.98 |              3751.45 |                 269.10 |                            333.23 |                               342.58 |                       0.58 |                                       0.48 |                  0.65 |                      0.45 |                  3.77 |                    0.82 |                               1.22 |                                  0.48 |                             0.88 |                                             0.77 |                        1.82 |                            3.28 |                        7.91 |                          1.52 |                                     1.56 |                                        0.76 |                   2314.47 |                                   5792.01 |               237.93 |                  2464.22 |              3653.00 |                 116.77 |                            172.15 |                               167.02 |                       0.30 |                                       0.30 |                  1.17 |                      2.82 |                  4.14 |                    0.70 |                               0.34 |                                  0.28 |
| ('gcn', 'artnet-views', 1, 512)  |                   2708.26 |                                   6185.80 |               630.74 |                  2854.59 |              5142.79 |                 511.33 |                            623.92 |                               633.27 |                       1.05 |                                       0.78 |                  1.08 |                      0.81 |                  7.65 |                    1.00 |                               1.52 |                                  0.83 |                             1.57 |                                             1.31 |                        2.50 |                            7.36 |                       15.47 |                          1.83 |                                     2.14 |                                        1.28 |                   2412.92 |                                   5890.46 |               431.72 |                  2562.91 |              4945.89 |                 213.66 |                            317.49 |                               289.30 |                       0.53 |                                       0.52 |                  1.42 |                      6.56 |                  7.83 |                    0.83 |                               0.62 |                                  0.45 |
| ('gcn', 'avazu-ctr', 1, 64)      |                   2288.59 |                                   5592.94 |              1288.66 |                  3255.39 |             14001.24 |                 506.50 |                           1919.91 |                              1029.65 |                       3.68 |                                       2.36 |                  2.73 |                     10.88 |                 31.81 |                  338.45 |                              16.06 |                                  2.71 |                             5.92 |                                             4.59 |                        5.98 |                           29.10 |                       66.00 |                        681.77 |                                    18.69 |                                        4.78 |                   2148.34 |                                   5452.49 |              1232.80 |                  3942.12 |             13964.00 |                 366.35 |                            559.68 |                               957.50 |                       2.24 |                                       2.23 |                  3.26 |                     18.23 |                 34.19 |                  343.32 |                               2.64 |                                  2.07 |
| ('gcn', 'avazu-ctr', 1, 128)     |                   2380.79 |                                   5688.31 |              1400.38 |                  3348.09 |             24839.72 |                 603.40 |                           1994.79 |                              1145.17 |                       6.38 |                                       2.96 |                  3.22 |                     19.93 |                 75.63 |                  342.22 |                              18.02 |                                  3.14 |                             9.06 |                                             5.77 |                        6.96 |                           47.58 |                      153.54 |                        691.30 |                                    21.02 |                                        5.47 |                   2269.07 |                                   5574.31 |              1288.66 |                  3960.73 |             24765.24 |                 405.11 |                            615.54 |                              1004.81 |                       2.68 |                                       2.81 |                  3.74 |                     27.65 |                 77.91 |                  349.08 |                               3.00 |                                  2.33 |
| ('gcn', 'avazu-ctr', 1, 256)     |                   2566.99 |                                   5872.24 |              1624.02 |                  3534.30 |             46516.69 |                 785.81 |                           2143.75 |                              1364.82 |                      11.70 |                                       5.17 |                  6.20 |                     16.21 |                158.46 |                  342.29 |                              19.14 |                                  5.73 |                            16.85 |                                            10.23 |                       12.62 |                           39.54 |                      316.35 |                        693.33 |                                    24.76 |                                        8.48 |                   2343.55 |                                   5648.80 |              1400.38 |                  3997.58 |             46367.72 |                 478.07 |                            727.26 |                              1097.15 |                       5.15 |                                       5.06 |                  6.41 |                     23.32 |                157.89 |                  351.03 |                               5.61 |                                  2.75 |
| ('gcn', 'avazu-ctr', 1, 512)     |                   2939.40 |                                   6244.65 |              2070.91 |                  3906.70 |               nan    |                1158.22 |                           2441.68 |                              1811.71 |                      22.29 |                                      10.17 |                 11.79 |                     32.90 |                nan    |                  341.79 |                              24.67 |                                 11.28 |                            32.08 |                                            19.95 |                       23.72 |                           73.19 |                      nan    |                        690.52 |                                    35.64 |                                       15.00 |                   2492.51 |                                   5797.76 |              1682.29 |                  4072.06 |               nan    |                 627.04 |                            950.70 |                              1283.35 |                       9.79 |                                       9.78 |                 11.93 |                     40.29 |                nan    |                  348.73 |                              10.97 |                                  3.72 |

In [38]:
print(build_raw_table_with_dataset_index(df[df[CONV_COL] == "gcn"], [CONV_COL, DATASET_COL, HEADS_COL, FEATURE_DIM_COL, REORDERING_COL]).to_markdown(floatfmt=".2f"))

|                                        |   ('Bwd mem', 'cusparse') |   ('Bwd mem', 'cusparse_precomputed_bwd') |   ('Bwd mem', 'dgl') |   ('Bwd mem', 'fusegnn') |   ('Bwd mem', 'pyg') |   ('Bwd mem', 'tcgnn') |   ('Bwd mem', 'torch_native_gcn') |   ('Bwd mem', 'triton_block_sparse') |   ('Bwd time', 'cusparse') |   ('Bwd time', 'cusparse_precomputed_bwd') |   ('Bwd time', 'dgl') |   ('Bwd time', 'fusegnn') |   ('Bwd time', 'pyg') |   ('Bwd time', 'tcgnn') |   ('Bwd time', 'torch_native_gcn') |   ('Bwd time', 'triton_block_sparse') |   ('Fwd + Bwd time', 'cusparse') |   ('Fwd + Bwd time', 'cusparse_precomputed_bwd') |   ('Fwd + Bwd time', 'dgl') |   ('Fwd + Bwd time', 'fusegnn') |   ('Fwd + Bwd time', 'pyg') |   ('Fwd + Bwd time', 'tcgnn') |   ('Fwd + Bwd time', 'torch_native_gcn') |   ('Fwd + Bwd time', 'triton_block_sparse') |   ('Fwd mem', 'cusparse') |   ('Fwd mem', 'cusparse_precomputed_bwd') |   ('Fwd mem', 'dgl') |   ('Fwd mem', 'fusegnn') |   ('Fwd mem', 'pyg') |   ('Fwd mem', 'tcgnn') |   ('Fwd mem', 'torch_native_gcn') |   ('Fwd mem', 'triton_block_sparse') |   ('Fwd time', 'cusparse') |   ('Fwd time', 'cusparse_precomputed_bwd') |   ('Fwd time', 'dgl') |   ('Fwd time', 'fusegnn') |   ('Fwd time', 'pyg') |   ('Fwd time', 'tcgnn') |   ('Fwd time', 'torch_native_gcn') |   ('Fwd time', 'triton_block_sparse') |
|:---------------------------------------|--------------------------:|------------------------------------------:|---------------------:|-------------------------:|---------------------:|-----------------------:|----------------------------------:|-------------------------------------:|---------------------------:|-------------------------------------------:|----------------------:|--------------------------:|----------------------:|------------------------:|-----------------------------------:|--------------------------------------:|---------------------------------:|-------------------------------------------------:|----------------------------:|--------------------------------:|----------------------------:|------------------------------:|-----------------------------------------:|--------------------------------------------:|--------------------------:|------------------------------------------:|---------------------:|-------------------------:|---------------------:|-----------------------:|----------------------------------:|-------------------------------------:|---------------------------:|-------------------------------------------:|----------------------:|--------------------------:|----------------------:|------------------------:|-----------------------------------:|--------------------------------------:|
| ('gcn', 'artnet-exp', 1, 64, -1)       |                     83.86 |                                     86.19 |               118.34 |                  2427.34 |              2713.42 |                  85.44 |                            111.88 |                               121.42 |                       0.23 |                                       0.27 |                  0.39 |                      0.29 |                  1.09 |                    0.67 |                               0.88 |                                  0.27 |                             0.40 |                                             0.45 |                        1.60 |                            4.29 |                        2.71 |                          1.17 |                                     1.07 |                                        0.51 |                     44.42 |                                     46.75 |                91.19 |                  2398.58 |              2688.81 |                  46.19 |                             63.88 |                                78.17 |                       0.17 |                                       0.17 |                  1.21 |                      4.00 |                  1.62 |                    0.50 |                               0.19 |                                  0.24 |
| ('gcn', 'artnet-exp', 1, 64, 128)      |                    nan    |                                     91.24 |               118.68 |                   nan    |               nan    |                 nan    |                            111.88 |                               nan    |                     nan    |                                       0.25 |                  0.39 |                    nan    |                nan    |                  nan    |                               0.91 |                                nan    |                           nan    |                                             0.42 |                        1.72 |                          nan    |                      nan    |                        nan    |                                     1.10 |                                      nan    |                    nan    |                                     51.80 |                91.19 |                   nan    |               nan    |                 nan    |                             63.88 |                               nan    |                     nan    |                                       0.17 |                  1.33 |                    nan    |                nan    |                  nan    |                               0.20 |                                nan    |
| ('gcn', 'artnet-exp', 1, 64, 512)      |                    nan    |                                     94.51 |               118.68 |                   nan    |               nan    |                 nan    |                            111.88 |                               nan    |                     nan    |                                       0.25 |                  0.39 |                    nan    |                nan    |                  nan    |                               0.87 |                                nan    |                           nan    |                                             0.43 |                        1.89 |                          nan    |                      nan    |                        nan    |                                     1.07 |                                      nan    |                    nan    |                                     54.32 |                91.19 |                   nan    |               nan    |                 nan    |                             63.88 |                               nan    |                     nan    |                                       0.18 |                  1.50 |                    nan    |                nan    |                  nan    |                               0.20 |                                nan    |
| ('gcn', 'artnet-exp', 1, 64, 1024)     |                    nan    |                                     94.51 |               118.68 |                   nan    |               nan    |                 nan    |                            111.88 |                               nan    |                     nan    |                                       0.25 |                  0.40 |                    nan    |                nan    |                  nan    |                               0.89 |                                nan    |                           nan    |                                             0.43 |                        2.41 |                          nan    |                      nan    |                        nan    |                                     1.09 |                                      nan    |                    nan    |                                     57.59 |                91.19 |                   nan    |               nan    |                 nan    |                             63.88 |                               nan    |                     nan    |                                       0.18 |                  2.01 |                    nan    |                nan    |                  nan    |                               0.20 |                                nan    |
| ('gcn', 'artnet-exp', 1, 64, 2048)     |                    nan    |                                     94.51 |               118.68 |                   nan    |               nan    |                 nan    |                            111.88 |                               nan    |                     nan    |                                       0.25 |                  0.40 |                    nan    |                nan    |                  nan    |                               0.89 |                                nan    |                           nan    |                                             0.42 |                        1.68 |                          nan    |                      nan    |                        nan    |                                     1.09 |                                      nan    |                    nan    |                                     57.59 |                91.19 |                   nan    |               nan    |                 nan    |                             63.88 |                               nan    |                     nan    |                                       0.18 |                  1.28 |                    nan    |                nan    |                  nan    |                               0.20 |                                nan    |
| ('gcn', 'artnet-exp', 1, 64, 4096)     |                    nan    |                                     94.51 |               118.68 |                   nan    |               nan    |                 nan    |                            111.88 |                               nan    |                     nan    |                                       0.25 |                  0.38 |                    nan    |                nan    |                  nan    |                               0.97 |                                nan    |                           nan    |                                             0.44 |                        1.79 |                          nan    |                      nan    |                        nan    |                                     1.16 |                                      nan    |                    nan    |                                     57.59 |                91.19 |                   nan    |               nan    |                 nan    |                             63.88 |                               nan    |                     nan    |                                       0.18 |                  1.41 |                    nan    |                nan    |                  nan    |                               0.19 |                                nan    |
| ('gcn', 'artnet-exp', 1, 64, 8192)     |                    nan    |                                     94.51 |               118.68 |                   nan    |               nan    |                 nan    |                            111.88 |                               nan    |                     nan    |                                       0.25 |                  0.38 |                    nan    |                nan    |                  nan    |                               0.88 |                                nan    |                           nan    |                                             0.43 |                        1.80 |                          nan    |                      nan    |                        nan    |                                     1.06 |                                      nan    |                    nan    |                                     57.59 |                91.19 |                   nan    |               nan    |                 nan    |                             63.88 |                               nan    |                     nan    |                                       0.18 |                  1.42 |                    nan    |                nan    |                  nan    |                               0.19 |                                nan    |
| ('gcn', 'artnet-exp', 1, 128, -1)      |                    145.39 |                                    147.72 |               192.18 |                  2489.02 |              3061.03 |                 146.96 |                            186.46 |                               195.25 |                       0.35 |                                       0.29 |                  0.45 |                      0.40 |                  2.04 |                    0.76 |                               0.93 |                                  0.32 |                             0.54 |                                             0.48 |                        1.59 |                            4.61 |                        4.57 |                          1.43 |                                     1.13 |                                        0.56 |                     71.55 |                                     73.89 |               140.41 |                  2419.92 |              3011.81 |                  70.80 |                            100.79 |                               108.93 |                       0.19 |                                       0.19 |                  1.14 |                      4.20 |                  2.53 |                    0.67 |                               0.20 |                                  0.25 |
| ('gcn', 'artnet-exp', 1, 128, 128)     |                    nan    |                                    152.77 |               192.51 |                   nan    |               nan    |                 nan    |                            186.46 |                               nan    |                     nan    |                                       0.30 |                  0.46 |                    nan    |                nan    |                  nan    |                               0.92 |                                nan    |                           nan    |                                             0.50 |                        1.61 |                          nan    |                      nan    |                        nan    |                                     1.12 |                                      nan    |                    nan    |                                     78.93 |               140.41 |                   nan    |               nan    |                 nan    |                            100.79 |                               nan    |                     nan    |                                       0.20 |                  1.15 |                    nan    |                nan    |                  nan    |                               0.20 |                                nan    |
| ('gcn', 'artnet-exp', 1, 128, 512)     |                    nan    |                                    156.04 |               192.51 |                   nan    |               nan    |                 nan    |                            186.46 |                               nan    |                     nan    |                                       0.29 |                  0.48 |                    nan    |                nan    |                  nan    |                               0.92 |                                nan    |                           nan    |                                             0.50 |                        1.62 |                          nan    |                      nan    |                        nan    |                                     1.12 |                                      nan    |                    nan    |                                     82.21 |               140.41 |                   nan    |               nan    |                 nan    |                            100.79 |                               nan    |                     nan    |                                       0.21 |                  1.14 |                    nan    |                nan    |                  nan    |                               0.20 |                                nan    |
| ('gcn', 'artnet-exp', 1, 128, 1024)    |                    nan    |                                    156.04 |               192.51 |                   nan    |               nan    |                 nan    |                            186.46 |                               nan    |                     nan    |                                       0.28 |                  0.48 |                    nan    |                nan    |                  nan    |                               0.93 |                                nan    |                           nan    |                                             0.49 |                        1.73 |                          nan    |                      nan    |                        nan    |                                     1.13 |                                      nan    |                    nan    |                                     82.21 |               140.41 |                   nan    |               nan    |                 nan    |                            100.79 |                               nan    |                     nan    |                                       0.20 |                  1.25 |                    nan    |                nan    |                  nan    |                               0.20 |                                nan    |
| ('gcn', 'artnet-exp', 1, 128, 2048)    |                    nan    |                                    156.04 |               192.51 |                   nan    |               nan    |                 nan    |                            186.46 |                               nan    |                     nan    |                                       0.29 |                  0.47 |                    nan    |                nan    |                  nan    |                               0.93 |                                nan    |                           nan    |                                             0.48 |                        1.61 |                          nan    |                      nan    |                        nan    |                                     1.13 |                                      nan    |                    nan    |                                     82.21 |               140.41 |                   nan    |               nan    |                 nan    |                            100.79 |                               nan    |                     nan    |                                       0.19 |                  1.14 |                    nan    |                nan    |                  nan    |                               0.20 |                                nan    |

## MinAggr

In [21]:
print(build_speedup_table_with_dataset_index(no_reordering_df[no_reordering_df[CONV_COL] == "min_aggr"], "dgl").to_markdown(floatfmt=".2f"))

|                                       |   ('Bwd mem', 'cuda') |   ('Bwd mem', 'cugraph') |   ('Bwd time', 'cuda') |   ('Bwd time', 'cugraph') |   ('Fwd + Bwd time', 'cuda') |   ('Fwd + Bwd time', 'cugraph') |   ('Fwd mem', 'cuda') |   ('Fwd mem', 'cugraph') |   ('Fwd time', 'cuda') |   ('Fwd time', 'cugraph') |
|:--------------------------------------|----------------------:|-------------------------:|-----------------------:|--------------------------:|-----------------------------:|--------------------------------:|----------------------:|-------------------------:|-----------------------:|--------------------------:|
| ('min_aggr', 'artnet-exp', 1, 64)     |                  1.41 |                     1.11 |                   1.26 |                      0.79 |                         1.67 |                            0.89 |                  1.67 |                     1.16 |                   2.26 |                      0.96 |
| ('min_aggr', 'artnet-exp', 1, 128)    |                  1.40 |                     1.14 |                   1.33 |                      0.98 |                         1.84 |                            1.14 |                  1.71 |                     1.21 |                   2.38 |                      1.25 |
| ('min_aggr', 'artnet-exp', 1, 256)    |                  1.38 |                     1.16 |                   1.45 |                      1.08 |                         1.98 |                            1.22 |                  1.71 |                     1.26 |                   2.57 |                      1.32 |
| ('min_aggr', 'artnet-exp', 1, 512)    |                  1.38 |                     1.17 |                   1.47 |                      1.19 |                         2.10 |                            1.28 |                  1.74 |                     1.28 |                   2.85 |                      1.34 |
| ('min_aggr', 'artnet-views', 1, 64)   |                  1.46 |                     1.12 |                   1.36 |                      1.11 |                         1.67 |                            1.12 |                  1.78 |                     1.17 |                   2.28 |                      1.13 |
| ('min_aggr', 'artnet-views', 1, 128)  |                  1.42 |                     1.14 |                   1.41 |                      0.87 |                         1.80 |                            1.10 |                  1.78 |                     1.22 |                   2.25 |                      1.30 |
| ('min_aggr', 'artnet-views', 1, 256)  |                  1.39 |                     1.16 |                   1.48 |                      1.16 |                         1.94 |                            1.27 |                  1.75 |                     1.26 |                   2.43 |                      1.35 |
| ('min_aggr', 'artnet-views', 1, 512)  |                  1.39 |                     1.17 |                   1.48 |                      1.25 |                         2.05 |                            1.29 |                  1.75 |                     1.29 |                   2.69 |                      1.32 |
| ('min_aggr', 'avazu-ctr', 1, 64)      |                  2.53 |                     0.94 |                   1.25 |                      0.84 |                         5.31 |                            0.54 |                  2.81 |                     0.93 |                   6.28 |                      0.54 |
| ('min_aggr', 'avazu-ctr', 1, 128)     |                  2.24 |                     0.97 |                   1.32 |                      0.39 |                         4.09 |                            0.59 |                  2.63 |                     0.96 |                   4.59 |                      0.61 |
| ('min_aggr', 'avazu-ctr', 1, 256)     |                  1.97 |                     1.01 |                   1.33 |                      0.97 |                         2.74 |                            0.36 |                  2.43 |                     1.01 |                   3.02 |                      0.34 |
| ('min_aggr', 'avazu-ctr', 1, 512)     |                  1.74 |                     1.06 |                   1.35 |                      1.10 |                         2.34 |                            0.29 |                  2.21 |                     1.07 |                   2.48 |                      0.28 |
| ('min_aggr', 'citeseer', 1, 64)       |                  1.04 |                     1.02 |                   1.65 |                      0.91 |                         2.49 |                            0.12 |                  1.04 |                     1.02 |                   4.32 |                      0.07 |
| ('min_aggr', 'citeseer', 1, 128)      |                  1.07 |                     1.03 |                   1.74 |                      0.68 |                         2.55 |                            0.97 |                  1.07 |                     1.04 |                   4.30 |                      1.54 |
| ('min_aggr', 'citeseer', 1, 256)      |                  1.11 |                     1.06 |                   2.03 |                      0.88 |                         2.52 |                            1.13 |                  1.13 |                     1.07 |                   4.26 |                      1.48 |
| ('min_aggr', 'citeseer', 1, 512)      |                  1.16 |                     1.09 |                   1.70 |                      0.98 |                         2.39 |                            1.07 |                  1.22 |                     1.12 |                   3.89 |                      1.17 |
| ('min_aggr', 'city-reviews', 1, 64)   |                  1.38 |                     1.08 |                   1.37 |                      1.17 |                         2.59 |                            0.62 |                  1.55 |                     1.11 |                   3.56 |                      0.56 |
| ('min_aggr', 'city-reviews', 1, 128)  |                  1.38 |                     1.12 |                   1.45 |                      1.12 |                         2.30 |                            0.74 |                  1.61 |                     1.17 |                   3.05 |                      0.66 |
| ('min_aggr', 'city-reviews', 1, 256)  |                  1.38 |                     1.14 |                   1.43 |                      1.20 |                         1.92 |                            0.53 |                  1.66 |                     1.22 |                   2.44 |                      0.41 |
| ('min_aggr', 'city-reviews', 1, 512)  |                  1.38 |                     1.16 |                   1.40 |                      1.18 |                         1.83 |                            0.56 |                  1.70 |                     1.26 |                   2.28 |                      0.43 |
| ('min_aggr', 'city-roads-L', 1, 64)   |                  1.26 |                     1.12 |                   1.30 |                      1.15 |                         1.44 |                            1.29 |                  1.38 |                     1.16 |                   1.84 |                      1.43 |
| ('min_aggr', 'city-roads-L', 1, 128)  |                  1.30 |                     1.14 |                   1.54 |                      1.30 |                         1.82 |                            1.74 |                  1.49 |                     1.21 |                   2.26 |                      2.36 |
| ('min_aggr', 'city-roads-L', 1, 256)  |                  1.33 |                     1.16 |                   1.58 |                      1.34 |                         2.01 |                            1.98 |                  1.60 |                     1.25 |                   2.70 |                      3.13 |
| ('min_aggr', 'city-roads-L', 1, 512)  |                  1.35 |                     1.17 |                   1.61 |                      1.38 |                         2.33 |                            2.12 |                  1.66 |                     1.28 |                   3.64 |                      3.50 |
| ('min_aggr', 'city-roads-M', 1, 64)   |                  1.34 |                     1.14 |                   1.35 |                      0.76 |                         1.61 |                            0.97 |                  1.58 |                     1.23 |                   2.06 |                      1.25 |
| ('min_aggr', 'city-roads-M', 1, 128)  |                  1.36 |                     1.16 |                   1.47 |                      1.00 |                         1.74 |                            0.35 |                  1.65 |                     1.26 |                   2.10 |                      0.23 |
| ('min_aggr', 'city-roads-M', 1, 256)  |                  1.37 |                     1.17 |                   1.60 |                      1.00 |                         1.97 |                            1.42 |                  1.70 |                     1.29 |                   2.43 |                      2.16 |
| ('min_aggr', 'city-roads-M', 1, 512)  |                  1.37 |                     1.17 |                   1.63 |                      1.00 |                         2.25 |                            1.55 |                  1.72 |                     1.30 |                   3.24 |                      2.78 |
| ('min_aggr', 'cora', 1, 64)           |                  1.09 |                     1.04 |                   1.59 |                      0.65 |                         2.39 |                            0.94 |                  1.10 |                     1.04 |                   4.14 |                      1.46 |
| ('min_aggr', 'cora', 1, 128)          |                  1.14 |                     1.07 |                   1.70 |                      0.85 |                         2.49 |                            1.12 |                  1.17 |                     1.08 |                   4.13 |                      1.51 |
| ('min_aggr', 'cora', 1, 256)          |                  1.20 |                     1.10 |                   1.83 |                      0.82 |                         2.46 |                            1.01 |                  1.27 |                     1.13 |                   4.10 |                      1.26 |
| ('min_aggr', 'cora', 1, 512)          |                  1.26 |                     1.13 |                   1.76 |                      0.85 |                         2.37 |                            0.91 |                  1.40 |                     1.18 |                   3.76 |                      0.96 |
| ('min_aggr', 'hm-categories', 1, 64)  |                  2.99 |                     0.92 |                   1.13 |                      0.97 |                         2.99 |                            0.52 |                  3.32 |                     0.92 |                   3.36 |                      0.51 |
| ('min_aggr', 'hm-categories', 1, 128) |                  2.68 |                     0.94 |                   1.25 |                      1.03 |                         2.22 |                            0.57 |                  3.13 |                     0.94 |                   2.37 |                      0.55 |
| ('min_aggr', 'hm-categories', 1, 256) |                  2.28 |                     0.98 |                   1.37 |                      1.10 |                         2.04 |                            0.50 |                  2.83 |                     0.98 |                   2.12 |                      0.48 |
| ('min_aggr', 'hm-categories', 1, 512) |                  1.95 |                     1.02 |                   1.37 |                      1.18 |                         1.93 |                            0.38 |                  2.51 |                     1.03 |                   1.98 |                      0.36 |
| ('min_aggr', 'hm-prices', 1, 64)      |                  2.81 |                     0.92 |                   1.22 |                      1.05 |                         3.06 |                            0.53 |                  3.08 |                     0.92 |                   3.44 |                      0.52 |
| ('min_aggr', 'hm-prices', 1, 128)     |                  2.56 |                     0.94 |                   1.40 |                      1.07 |                         2.28 |                            0.58 |                  2.94 |                     0.94 |                   2.42 |                      0.56 |
| ('min_aggr', 'hm-prices', 1, 256)     |                  2.22 |                     0.98 |                   1.37 |                      1.08 |                         2.14 |                            0.52 |                  2.70 |                     0.98 |                   2.23 |                      0.50 |
| ('min_aggr', 'hm-prices', 1, 512)     |                  1.92 |                     1.02 |                   1.39 |                      1.20 |                         1.99 |                            0.39 |                  2.44 |                     1.03 |                   2.05 |                      0.37 |
| ('min_aggr', 'ogbn-arxiv', 1, 64)     |                  1.35 |                     1.12 |                   2.60 |                      1.78 |                         4.60 |                            3.27 |                  1.55 |                     1.16 |                   6.42 |                      4.31 |
| ('min_aggr', 'ogbn-arxiv', 1, 128)    |                  1.36 |                     1.14 |                   2.19 |                      1.70 |                         3.83 |                            3.27 |                  1.62 |                     1.22 |                   5.47 |                      4.79 |
| ('min_aggr', 'ogbn-arxiv', 1, 256)    |                  1.37 |                     1.16 |                   2.19 |                      1.82 |                         3.18 |                            2.74 |                  1.67 |                     1.26 |                   4.28 |                      3.69 |
| ('min_aggr', 'ogbn-arxiv', 1, 512)    |                  1.37 |                     1.17 |                   1.81 |                      1.45 |                         2.61 |                            2.12 |                  1.71 |                     1.28 |                   3.54 |                      2.87 |
| ('min_aggr', 'ogbn-products', 1, 64)  |                  1.76 |                     1.03 |                   1.16 |                      1.11 |                         1.55 |                            0.76 |                  2.12 |                     1.04 |                   1.82 |                      0.67 |
| ('min_aggr', 'ogbn-products', 1, 128) |                  1.61 |                     1.08 |                   1.15 |                      1.08 |                         1.42 |                            1.08 |                  2.00 |                     1.10 |                   1.63 |                      1.07 |
| ('min_aggr', 'ogbn-products', 1, 256) |                  1.50 |                     1.11 |                   1.18 |                      1.09 |                         1.36 |                            1.07 |                  1.90 |                     1.17 |                   1.49 |                      1.07 |
| ('min_aggr', 'ogbn-products', 1, 512) |                  1.44 |                     1.14 |                   1.17 |                      1.09 |                         1.33 |                            1.07 |                  1.83 |                     1.23 |                   1.45 |                      1.05 |
| ('min_aggr', 'pokec-regions', 1, 64)  |                  1.53 |                     1.09 |                   1.38 |                      1.14 |                         1.69 |                            0.91 |                  1.88 |                     1.13 |                   2.00 |                      0.80 |
| ('min_aggr', 'pokec-regions', 1, 128) |                  1.46 |                     1.13 |                   1.29 |                      1.17 |                         1.64 |                            1.29 |                  1.83 |                     1.19 |                   2.04 |                      1.40 |
| ('min_aggr', 'pokec-regions', 1, 256) |                  1.42 |                     1.15 |                   1.35 |                      1.16 |                         1.61 |                            1.30 |                  1.79 |                     1.24 |                   1.93 |                      1.43 |
| ('min_aggr', 'pokec-regions', 1, 512) |                  1.40 |                     1.16 |                   1.28 |                      1.14 |                         1.57 |                            1.28 |                  1.77 |                     1.27 |                   1.90 |                      1.42 |
| ('min_aggr', 'pubmed', 1, 64)         |                  1.19 |                     1.07 |                   1.41 |                      0.59 |                         2.03 |                            1.04 |                  1.25 |                     1.11 |                   3.81 |                      2.00 |
| ('min_aggr', 'pubmed', 1, 128)        |                  1.24 |                     1.11 |                   1.50 |                      0.88 |                         1.92 |                            1.06 |                  1.35 |                     1.15 |                   2.63 |                      1.29 |
| ('min_aggr', 'pubmed', 1, 256)        |                  1.28 |                     1.14 |                   1.26 |                      0.93 |                         1.75 |                            1.03 |                  1.46 |                     1.20 |                   2.42 |                      1.12 |
| ('min_aggr', 'pubmed', 1, 512)        |                  1.33 |                     1.15 |                   1.43 |                      1.07 |                         1.95 |                            1.14 |                  1.58 |                     1.24 |                   2.69 |                      1.19 |
| ('min_aggr', 'tolokers-2', 1, 64)     |                  2.10 |                     0.98 |                   1.55 |                      0.84 |                         1.91 |                            0.66 |                  2.71 |                     0.99 |                   2.48 |                      0.60 |
| ('min_aggr', 'tolokers-2', 1, 128)    |                  1.85 |                     1.04 |                   1.75 |                      0.66 |                         2.34 |                            0.72 |                  2.39 |                     1.06 |                   2.90 |                      0.75 |
| ('min_aggr', 'tolokers-2', 1, 256)    |                  1.61 |                     1.09 |                   1.58 |                      0.87 |                         2.01 |                            0.62 |                  2.10 |                     1.13 |                   2.36 |                      0.57 |
| ('min_aggr', 'tolokers-2', 1, 512)    |                  1.51 |                     1.12 |                   1.32 |                      0.87 |                         1.73 |                            0.48 |                  1.97 |                     1.19 |                   2.01 |                      0.44 |
| ('min_aggr', 'twitch-views', 1, 64)   |                  2.06 |                     1.00 |                   1.30 |                      1.01 |                         4.15 |                            0.56 |                  2.61 |                     1.00 |                   5.10 |                      0.55 |

In [21]:
print(build_raw_table_with_dataset_index(no_reordering_df[no_reordering_df[CONV_COL] == "min_aggr"]).to_markdown(floatfmt=".2f"))

|                                       |   ('Bwd mem', 'cuda') |   ('Bwd mem', 'cugraph') |   ('Bwd mem', 'dgl') |   ('Bwd time', 'cuda') |   ('Bwd time', 'cugraph') |   ('Bwd time', 'dgl') |   ('Fwd + Bwd time', 'cuda') |   ('Fwd + Bwd time', 'cugraph') |   ('Fwd + Bwd time', 'dgl') |   ('Fwd mem', 'cuda') |   ('Fwd mem', 'cugraph') |   ('Fwd mem', 'dgl') |   ('Fwd time', 'cuda') |   ('Fwd time', 'cugraph') |   ('Fwd time', 'dgl') |
|:--------------------------------------|----------------------:|-------------------------:|---------------------:|-----------------------:|--------------------------:|----------------------:|-----------------------------:|--------------------------------:|----------------------------:|----------------------:|-------------------------:|---------------------:|-----------------------:|--------------------------:|----------------------:|
| ('min_aggr', 'artnet-exp', 1, 64)     |                 94.94 |                   120.73 |               133.97 |                   0.21 |                      0.33 |                  0.26 |                         0.42 |                            0.78 |                        0.70 |                 58.03 |                    83.81 |                97.05 |                   0.19 |                      0.45 |                  0.43 |
| ('min_aggr', 'artnet-exp', 1, 128)    |                168.78 |                   207.65 |               236.27 |                   0.24 |                      0.32 |                  0.32 |                         0.48 |                            0.77 |                        0.88 |                 94.94 |                   133.81 |               162.44 |                   0.24 |                      0.45 |                  0.57 |
| ('min_aggr', 'artnet-exp', 1, 256)    |                321.11 |                   383.03 |               443.20 |                   0.38 |                      0.51 |                  0.55 |                         0.76 |                            1.22 |                        1.50 |                171.11 |                   233.03 |               293.20 |                   0.37 |                      0.72 |                  0.95 |
| ('min_aggr', 'artnet-exp', 1, 512)    |                611.79 |                   723.72 |               844.64 |                   0.71 |                      0.88 |                  1.05 |                         1.35 |                            2.20 |                        2.83 |                316.45 |                   428.38 |               549.30 |                   0.62 |                      1.33 |                  1.78 |
| ('min_aggr', 'artnet-views', 1, 64)   |                 89.22 |                   116.67 |               130.27 |                   0.21 |                      0.26 |                  0.29 |                         0.44 |                            0.66 |                        0.73 |                 52.30 |                    79.75 |                93.36 |                   0.20 |                      0.40 |                  0.45 |
| ('min_aggr', 'artnet-views', 1, 128)  |                163.06 |                   203.59 |               232.23 |                   0.23 |                      0.37 |                  0.33 |                         0.48 |                            0.79 |                        0.87 |                 89.22 |                   129.75 |               158.40 |                   0.24 |                      0.42 |                  0.54 |
| ('min_aggr', 'artnet-views', 1, 256)  |                315.38 |                   378.98 |               439.16 |                   0.38 |                      0.48 |                  0.56 |                         0.75 |                            1.15 |                        1.46 |                165.38 |                   228.98 |               289.16 |                   0.37 |                      0.67 |                  0.90 |
| ('min_aggr', 'artnet-views', 1, 512)  |                606.07 |                   719.66 |               840.60 |                   0.71 |                      0.84 |                  1.05 |                         1.34 |                            2.12 |                        2.74 |                310.73 |                   424.32 |               545.26 |                   0.63 |                      1.28 |                  1.69 |
| ('min_aggr', 'avazu-ctr', 1, 64)      |                357.40 |                   963.17 |               903.76 |                   0.39 |                      0.58 |                  0.49 |                         2.45 |                           23.28 |                       12.67 |                301.54 |                   907.31 |               847.90 |                   2.03 |                     22.69 |                 12.18 |
| ('min_aggr', 'avazu-ctr', 1, 128)     |                473.67 |                  1094.27 |              1061.17 |                   0.49 |                      1.67 |                  0.65 |                         3.32 |                           22.92 |                       13.59 |                359.67 |                   981.79 |               947.17 |                   2.82 |                     21.25 |                 12.94 |
| ('min_aggr', 'avazu-ctr', 1, 256)     |                692.56 |                  1354.20 |              1363.85 |                   0.80 |                      1.10 |                  1.07 |                         5.51 |                           42.46 |                       15.11 |                469.12 |                  1130.76 |              1140.41 |                   4.65 |                     41.36 |                 14.04 |
| ('min_aggr', 'avazu-ctr', 1, 512)     |               1139.45 |                  1875.64 |              1979.16 |                   1.35 |                      1.66 |                  1.83 |                        10.90 |                           87.14 |                       25.51 |                692.56 |                  1428.76 |              1532.27 |                   9.54 |                     85.48 |                 23.68 |
| ('min_aggr', 'citeseer', 1, 64)       |                 52.02 |                    53.06 |                54.04 |                   0.17 |                      0.31 |                  0.28 |                         0.25 |                            5.06 |                        0.62 |                 49.58 |                    50.62 |                51.60 |                   0.08 |                      4.75 |                  0.34 |
| ('min_aggr', 'citeseer', 1, 128)      |                 56.89 |                    58.74 |                60.74 |                   0.16 |                      0.42 |                  0.28 |                         0.24 |                            0.63 |                        0.62 |                 52.01 |                    53.87 |                55.87 |                   0.08 |                      0.22 |                  0.33 |
| ('min_aggr', 'citeseer', 1, 256)      |                 67.14 |                    70.62 |                74.65 |                   0.14 |                      0.32 |                  0.28 |                         0.24 |                            0.54 |                        0.61 |                 56.89 |                    60.37 |                64.40 |                   0.08 |                      0.23 |                  0.33 |
| ('min_aggr', 'citeseer', 1, 512)      |                 87.14 |                    93.36 |               101.45 |                   0.17 |                      0.29 |                  0.28 |                         0.26 |                            0.58 |                        0.62 |                 67.14 |                    73.36 |                81.96 |                   0.09 |                      0.29 |                  0.34 |
| ('min_aggr', 'city-reviews', 1, 64)   |                355.02 |                   453.89 |               490.73 |                   0.35 |                      0.41 |                  0.47 |                         1.01 |                            3.88 |                        2.42 |                246.03 |                   344.90 |               381.74 |                   0.65 |                      3.47 |                  1.95 |
| ('min_aggr', 'city-reviews', 1, 128)  |                572.99 |                   708.87 |               791.12 |                   0.63 |                      0.81 |                  0.91 |                         1.53 |                            4.55 |                        3.36 |                355.02 |                   490.90 |               573.15 |                   0.89 |                      3.74 |                  2.45 |
| ('min_aggr', 'city-reviews', 1, 256)  |               1013.05 |                  1220.22 |              1393.97 |                   1.30 |                      1.55 |                  1.86 |                         2.82 |                           10.04 |                        5.31 |                575.05 |                   782.22 |               955.97 |                   1.51 |                      8.49 |                  3.45 |
| ('min_aggr', 'city-reviews', 1, 512)  |               1880.81 |                  2234.72 |              2589.44 |                   2.80 |                      3.33 |                  3.93 |                         5.65 |                           18.38 |                       10.33 |               1008.93 |                  1362.84 |              1717.55 |                   2.82 |                     15.05 |                  6.40 |
| ('min_aggr', 'city-roads-L', 1, 64)   |                326.55 |                   368.73 |               411.26 |                   0.31 |                      0.35 |                  0.41 |                         0.66 |                            0.71 |                        0.92 |                222.36 |                   264.54 |               307.07 |                   0.29 |                      0.36 |                  0.51 |
| ('min_aggr', 'city-roads-L', 1, 128)  |                538.17 |                   614.00 |               700.48 |                   0.45 |                      0.54 |                  0.70 |                         0.87 |                            0.91 |                        1.58 |                328.17 |                   404.00 |               490.48 |                   0.40 |                      0.37 |                  0.89 |
| ('min_aggr', 'city-roads-L', 1, 256)  |                951.70 |                  1097.69 |              1270.46 |                   0.80 |                      0.94 |                  1.26 |                         1.45 |                            1.47 |                        2.92 |                534.93 |                   680.92 |               853.69 |                   0.64 |                      0.53 |                  1.65 |
| ('min_aggr', 'city-roads-L', 1, 512)  |               1786.17 |                  2071.07 |              2418.19 |                   1.49 |                      1.73 |                  2.39 |                         2.44 |                            2.65 |                        5.61 |                952.17 |                  1237.07 |              1584.19 |                   0.93 |                      0.92 |                  3.22 |
| ('min_aggr', 'city-roads-M', 1, 64)   |                101.00 |                   118.39 |               135.52 |                   0.22 |                      0.39 |                  0.30 |                         0.40 |                            0.66 |                        0.64 |                 59.07 |                    76.39 |                93.58 |                   0.17 |                      0.28 |                  0.35 |
| ('min_aggr', 'city-roads-M', 1, 128)  |                185.07 |                   216.39 |               251.13 |                   0.24 |                      0.36 |                  0.36 |                         0.46 |                            2.26 |                        0.79 |                101.07 |                   132.39 |               167.13 |                   0.21 |                      1.90 |                  0.44 |
| ('min_aggr', 'city-roads-M', 1, 256)  |                353.07 |                   412.39 |               482.10 |                   0.38 |                      0.60 |                  0.60 |                         0.68 |                            0.94 |                        1.34 |                185.07 |                   244.39 |               314.10 |                   0.31 |                      0.35 |                  0.74 |
| ('min_aggr', 'city-roads-M', 1, 512)  |                689.07 |                   803.33 |               943.11 |                   0.67 |                      1.09 |                  1.09 |                         1.10 |                            1.59 |                        2.47 |                353.07 |                   467.33 |               607.11 |                   0.43 |                      0.50 |                  1.38 |
| ('min_aggr', 'cora', 1, 64)           |                 18.91 |                    19.84 |                20.63 |                   0.18 |                      0.43 |                  0.28 |                         0.26 |                            0.66 |                        0.62 |                 16.93 |                    17.86 |                18.65 |                   0.08 |                      0.23 |                  0.34 |
| ('min_aggr', 'cora', 1, 128)          |                 22.88 |                    24.47 |                26.08 |                   0.16 |                      0.33 |                  0.28 |                         0.25 |                            0.55 |                        0.62 |                 18.91 |                    20.51 |                22.12 |                   0.08 |                      0.22 |                  0.34 |
| ('min_aggr', 'cora', 1, 256)          |                 30.81 |                    33.73 |                36.99 |                   0.15 |                      0.34 |                  0.28 |                         0.25 |                            0.61 |                        0.62 |                 22.88 |                    25.79 |                29.06 |                   0.08 |                      0.27 |                  0.34 |
| ('min_aggr', 'cora', 1, 512)          |                 46.68 |                    52.24 |                58.91 |                   0.16 |                      0.33 |                  0.28 |                         0.27 |                            0.70 |                        0.64 |                 30.81 |                    36.37 |                43.04 |                   0.09 |                      0.37 |                  0.35 |
| ('min_aggr', 'hm-categories', 1, 64)  |                259.02 |                   839.61 |               773.90 |                   0.27 |                      0.32 |                  0.31 |                         2.29 |                           11.72 |                        6.11 |                223.02 |                   805.50 |               739.79 |                   1.98 |                     11.40 |                  5.80 |
| ('min_aggr', 'hm-categories', 1, 128) |                323.44 |                   919.18 |               866.94 |                   0.35 |                      0.42 |                  0.44 |                         3.08 |                           12.04 |                        6.82 |                255.23 |                   850.97 |               798.74 |                   2.71 |                     11.61 |                  6.38 |
| ('min_aggr', 'hm-categories', 1, 256) |                463.02 |                  1078.86 |              1057.79 |                   0.52 |                      0.65 |                  0.72 |                         4.89 |                           19.86 |                        9.96 |                325.02 |                   941.92 |               919.79 |                   4.36 |                     19.21 |                  9.24 |
| ('min_aggr', 'hm-categories', 1, 512) |                732.68 |                  1396.75 |              1429.24 |                   0.87 |                      1.01 |                  1.19 |                        10.13 |                           51.95 |                       19.55 |                459.85 |                  1123.92 |              1156.41 |                   9.25 |                     50.94 |                 18.36 |
| ('min_aggr', 'hm-prices', 1, 64)      |                283.92 |                   865.19 |               798.79 |                   0.28 |                      0.33 |                  0.34 |                         2.27 |                           11.77 |                        6.28 |                247.92 |                   831.08 |               764.68 |                   1.99 |                     11.44 |                  5.94 |
| ('min_aggr', 'hm-prices', 1, 128)     |                348.33 |                   944.76 |               891.84 |                   0.35 |                      0.46 |                  0.49 |                         3.08 |                           12.16 |                        7.04 |                280.12 |                   876.55 |               823.63 |                   2.72 |                     11.70 |                  6.55 |
| ('min_aggr', 'hm-prices', 1, 256)     |                487.92 |                  1104.97 |              1082.68 |                   0.53 |                      0.67 |                  0.72 |                         4.81 |                           19.92 |                       10.27 |                349.92 |                   967.50 |               944.68 |                   4.27 |                     19.25 |                  9.54 |
| ('min_aggr', 'hm-prices', 1, 512)     |                757.58 |                  1422.33 |              1454.13 |                   0.87 |                      1.00 |                  1.20 |                        10.14 |                           52.26 |                       20.15 |                484.75 |                  1149.50 |              1181.30 |                   9.25 |                     51.26 |                 18.95 |
| ('min_aggr', 'ogbn-arxiv', 1, 64)     |                347.32 |                   419.82 |               468.27 |                   0.35 |                      0.51 |                  0.91 |                         0.95 |                            1.25 |                        4.08 |                221.32 |                   293.82 |               342.27 |                   0.59 |                      0.73 |                  3.16 |
| ('min_aggr', 'ogbn-arxiv', 1, 128)    |                591.44 |                   706.57 |               805.28 |                   0.59 |                      0.77 |                  1.30 |                         1.39 |                            1.56 |                        5.10 |                343.38 |                   458.51 |               557.22 |                   0.79 |                      0.79 |                  3.80 |
| ('min_aggr', 'ogbn-arxiv', 1, 256)    |               1091.32 |                  1287.89 |              1491.23 |                   1.16 |                      1.39 |                  2.53 |                         2.42 |                            2.74 |                        7.50 |                593.32 |                   789.89 |               993.23 |                   1.25 |                      1.35 |                  4.97 |

In [22]:
import pandas as pd

In [23]:
gt_kernel_ncu = pd.read_csv("../gt_profile.csv")
gt_kernel_ncu

,ID,Process ID,Process Name,Host Name,Kernel Name,Context,Stream,Block Size,Grid Size,Device,...,smsp__warps_active.min.peak_sustained,smsp__warps_active.min.per_cycle_active,smsp__warps_active.sum.peak_sustained,smsp__warps_active.sum.per_cycle_active,smsp__warps_eligible.avg.per_cycle_active,smsp__warps_eligible.max.per_cycle_active,smsp__warps_eligible.min.per_cycle_active,smsp__warps_eligible.sum.per_cycle_active,thread_inst_executed,thread_inst_executed_true
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,warp,warp,warp,warp,warp,warp,warp,warp,inst,inst
1,0.0,2235973.0,python3.11,127.0.0.1,"GraphAttentionForward_CSR_MH(unsigned long, un...",1.0,7.0,"(32, 1, 1)","(500, 1, 1)",0.0,...,16,0.66,6912,495.97,0.09,0.24,0.04,40.20,26531000,25394500
2,1.0,2235973.0,python3.11,127.0.0.1,"GraphAttentionForward_CSR_MH(unsigned long, un...",1.0,7.0,"(32, 1, 1)","(500, 1, 1)",0.0,...,16,0.65,6912,496.06,0.09,0.24,0.04,40.10,26531000,25394500

In [13]:
df_test = pd.read_csv("../test_partition", index_col=0)

In [18]:
df_test

,conv_type,dataset,backend,num_nodes,num_edges,avg_node_degree,feature_dim,heads,forward_ms,forward_memory_mb,backward_ms,backward_memory_mb,graph_reordering_partition_size,device_name,device_total_memory_mb,sm_count,compute_capability,max_threads_per_sm,registers_per_sm,experiment_name
0,gt,artnet-views,dgl,50405,560696,0.089897,512,2,6.940263,746.346191,14.908826,1443.795898,-1,NVIDIA A100-SXM4-80GB,81152.75,108,8.0,2048,65536,gt_dgl_artnet-views_feature_dim_512_heads_2
1,gt,artnet-views,dgl,50405,560696,0.089897,512,2,6.948045,744.975586,14.963609,1442.425293,32,NVIDIA A100-SXM4-80GB,81152.75,108,8.0,2048,65536,gt_dgl_artnet-views_feature_dim_512_heads_2
2,gt,artnet-views,dgl,50405,560696,0.089897,512,2,6.960128,744.975586,14.965555,1442.425293,64,NVIDIA A100-SXM4-80GB,81152.75,108,8.0,2048,65536,gt_dgl_artnet-views_feature_dim_512_heads_2
3,gt,artnet-views,dgl,50405,560696,0.089897,512,2,6.961766,744.975586,14.965248,1442.425293,128,NVIDIA A100-SXM4-80GB,81152.75,108,8.0,2048,65536,gt_dgl_artnet-views_feature_dim_512_heads_2
4,gt,artnet-views,dgl,50405,560696,0.089897,512,2,6.948864,744.975586,15.013991,1442.425293,256,NVIDIA A100-SXM4-80GB,81152.75,108,8.0,2048,65536,gt_dgl_artnet-views_feature_dim_512_heads_2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,gt,twitch-views,triton_block_sparse,168114,13595114,0.012366,512,2,34.644992,2901.062500,399.700586,4546.763672,512,NVIDIA A100-SXM4-80GB,81152.75,108,8.0,2048,65536,gt_triton_block_sparse_twitch-views_feature_di...
176,gt,twitch-views,triton_block_sparse,168114,13595114,0.012366,512,2,32.287949,2896.116699,429.360010,4541.817871,1024,NVIDIA A100-SXM4-80GB,81152.75,108,8.0,2048,65536,gt_triton_block_sparse_twitch-views_feature_di...
177,gt,twitch-views,triton_block_sparse,168114,13595114,0.012366,512,2,34.328168,2890.816406,422.754297,4536.517578,4096,NVIDIA A100-SXM4-80GB,81152.75,108,8.0,2048,65536,gt_triton_block_sparse_twitch-views_feature_di...
178,gt,twitch-views,triton_block_sparse,168114,13595114,0.012366,512,2,33.651303,2881.969238,385.971704,4527.670410,8192,NVIDIA A100-SXM4-80GB,81152.75,108,8.0,2048,65536,gt_triton_block_sparse_twitch-views_feature_di...
179,gt,twitch-views,triton_block_sparse,168114,13595114,0.012366,512,2,32.341196,2879.636719,417.744385,4525.337891,16384,NVIDIA A100-SXM4-80GB,81152.75,108,8.0,2048,65536,gt_triton_block_sparse_twitch-views_feature_di...

In [21]:
df_test["graph_reordering_partition_size"] = df_test["graph_reordering_partition_size"].astype(str)

In [22]:
for dataset in df_test[DATASET_COL].unique():
    df_dataset = df_test[df_test[DATASET_COL] == dataset]
    fig = px.scatter(df_dataset, x="graph_reordering_partition_size", y=FWD_MS_COL, title=dataset, color=BACKEND_COL)
    fig.show()